### ISSUE TITLE
Animating Header Elements When Using FixedPixelsTop

### ISSUE THREAD

**Issue by tskweres** [shprink/ionic-native-transitions#103]
If I have an app with a header, I want to animate pages using fixedPixelsTop: 44, but when I do this I lose the animation of the ionic title and header buttons. 

Any idea how to achieve the header animation while using native animations for the pages below?

**Comment by shprink** [comment]
You can enable both animations

https://github.com/shprink/ionic-native-transitions#enabledisable-optional

`$ionicNativeTransitions.enable(true, false);`

**Comment by tskweres** [comment]
Oh wow, thanks, works perfectly. 👍 

I was about to write a custom provider to re-insert and animate my own header elements :(

**Comment by shprink** [comment]
It is all in the docs :)
