### ISSUE TITLE
Blink and Lag

### ISSUE THREAD

**Issue by willianbs** [shprink/ionic-native-transitions#11]
Hi, there's a way to remove the 'blinking' when transition starts? 
I'm already using $ionicConfigProvider.views.transition('none'); to disable ionic default transitions.

Versions used:
Telerik Native Transitions Plugin @ is 0.4.3
ionic-native-transitions @ 1.0.0-beta5

(and when I set $ionicNativeTransitionsProvider.setOptions, the app does not load)

**Comment by shprink** [comment]
`setOptions` does not exist anymore. Use `$ionicNativeTransitionsProvider.setDefaultOptions`

Also `$ionicConfigProvider.views.transition('none'); ` is already set when using ionic-native-transitions

**Comment by willianbs** [comment]
Thanks, now its smooth :)

**Comment by shprink** [comment]
That's cool. On which OS are you testing?

**Comment by shprink** [comment]
and BTW it is not recommended to use `$ionicNativeTransitionsProvider.setDefaultOptions`, the default options should be sufficient for your needs.

**Comment by willianbs** [comment]
iOS 9.02 - iPhone 6. Gonna try Android 4.3 later today.

I'm using:
```javascript
$ionicNativeTransitionsProvider.setDefaultOptions({
            "duration": 400, // in milliseconds (ms), default 400,
            "slowdownfactor": 4, // overlap views (higher number is more) or no overlap (1), default 4
            "iosdelay":60, // ms to wait for the iOS webview to update before animation kicks in, default -1
            "androiddelay": 70, // same as above but for Android, default -1
            "winphonedelay": 200, // same as above but for Windows Phone, default -1,
            "fixedPixelsTop": 0, // the number of pixels of your fixed header, default 0 (iOS and Android)
            "fixedPixelsBottom": 0, // the number of pixels of your fixed footer (f.i. a tab bar), default 0 (iOS and Android)
            "triggerTransitionEvent": '$ionicView.afterEnter' // internal ionic-native-transitions option
        });

```

And it's working smooth. Default options were causing the "blink" effect.
