### ISSUE TITLE
Failed to instantiate module ionic-native-transitions

### ISSUE THREAD

**Issue by joshualzb** [shprink/ionic-native-transitions#110]
angular.module('starter', ['ionic', 'starter.controllers', 'starter.services', 'ionic-native-transitions'])
.config(function ($stateProvider, $ionicConfigProvider, $urlRouterProvider, $ionicNativeTransitionsProvider) {
$ionicNativeTransitionsProvider.setDefaultOptions({
            duration: 400, // in milliseconds (ms), default 400,
            slowdownfactor: 4, // overlap views (higher number is more) or no overlap (1), default 4
            iosdelay: -1, // ms to wait for the iOS webview to update before animation kicks in, default -1
            androiddelay: -1, // same as above but for Android, default -1
            winphonedelay: -1, // same as above but for Windows Phone, default -1,
            fixedPixelsTop: 0, // the number of pixels of your fixed header, default 0 (iOS and Android)
            fixedPixelsBottom: 0, // the number of pixels of your fixed footer (f.i. a tab bar), default 0 (iOS and Android)
            triggerTransitionEvent: '$ionicView.afterEnter', // internal ionic-native-transitions option
            backInOppositeDirection: false // Takes over default back transition and state back transition to use the opposite direction transition to go back
        });
}

log
---------------------------------------------------------------

I/chromium(18055): [INFO:CONSOLE(17917)] "Uncaught Error: [$injector:modulerr] Failed to instantiate module starter due to:
I/chromium(18055): Error: [$injector:modulerr] Failed to instantiate module ionic-native-transitions due to:
I/chromium(18055): Error: [$injector:nomod] Module 'ionic-native-transitions' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
I/chromium(18055): http://errors.angularjs.org/1.5.3/$injector/nomod?p0=ionic-native-transitions
I/chromium(18055):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:13438:12
I/chromium(18055):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:15404:17
I/chromium(18055):     at ensure (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:15328:38)
I/chromium(18055):     at module (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:15402:14)
I/chromium(18055):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:17894:22
I/chromium(18055):     at forEach (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:13691:20)
I/chromium(18055):     at loadModules (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:17878:5)
I/chromium(18055):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:17895:40
I/chromium(18055):     at forEach (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:13691:20)
I/chromium(18055):     at loadModules (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:17878:5)

---------------------------------------------------------------

**Comment by shprink** [comment]
> Module 'ionic-native-transitions' is not available! You either misspelled the module name or forgot to load it.

You forgot to include the lib in your app.
