### ISSUE TITLE
CDVLocalStorage

### ISSUE THREAD

**Issue by clewsk8er** [shprink/ionic-native-transitions#116]
I have recently installed this plugin using the steps provided and I am now getting an error on the build that says the CDVLocalStorage file is not found. It is in the CordovaLib/classes/private/plugins folder. Is there anything I should do to give the plugin permission to use it?

**Comment by shprink** [comment]
I do not think it is related to this plugin. please check on https://github.com/Telerik-Verified-Plugins/NativePageTransitions

**Comment by clewsk8er** [comment]
It is. Your plugin is not compatible with Cordova ios 4.1.1 I saw it later.
Thanks for your time. I will most likely use this once it is updated.
