### ISSUE TITLE
Xcode Build failed

### ISSUE THREAD

**Issue by kingkarki** [shprink/ionic-native-transitions#117]
Build failed 

* BUILD FAILED **

The following build commands failed:
	CompileC build/Mobileapp.build/Debug-iphonesimulator/Mobileapp.build/Objects-normal/i386/MyMainViewController.o Mobileapp/Plugins/com.telerik.plugins.wkwebview/MyMainViewController.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Applications/apps/band/platforms/ios/cordova/build-debug.xcconfig,-project,Mobileapp.xcodeproj,ARCHS=i386,-target,Mobileapp,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Applications/apps/band/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Applications/apps/band/platforms/ios/build/sharedpch

My Environment
Ionic version: 1.7.14
Cordova version: 6.1.1
Xcode: 7.3

Installed plugins:
rishnak:band krishnak$ cordova plugin ls
com.bunkerpalace.cordova.YoutubeVideoPlayer 1.0.1 "CordovaYoutubeVideoPlayer"
com.telerik.plugins.nativepagetransitions 0.6.2 "Native Page Transitions"
com.telerik.plugins.wkwebview 0.6.9 "WKWebView Polyfill"
cordova-plugin-admobpro 2.17.0 "AdMob Plugin Pro"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-extension 1.5.1 "Cordova Plugin Extension"
cordova-plugin-facebook4 1.7.1 "Facebook Connect"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-fullscreen 1.1.0 "cordova-plugin-fullscreen"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 3.2.1 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-webserver 1.0.3 "CordovaWebServer"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.0 "SocialSharing"
cordova-sqlite-storage 1.2.1 "Cordova sqlite storage plugin (core version)"
ionic-plugin-keyboard 2.1.0 "Keyboard"
phonegap-plugin-push 1.6.2 "PushPlugin"

**Comment by shprink** [comment]
All iOS or Android compilation problem could be related to the cordova plugin => https://github.com/Telerik-Verified-Plugins/NativePageTransitions

try to create the issue over there.

**Comment by kingkarki** [comment]
Yes it was due to this plugin com.telerik.plugins.wkwebview 0.6.9 "WKWebView Polyfill". 

Is it necessary to have wkwebview plugin to run this plugin?

**Comment by shprink** [comment]
not at all

**Comment by rohanpadwalkar** [comment]
facing same problem

**Comment by kingkarki** [comment]
@rohanpadwalkar don't waste your time on this plugin if you are using ionic. It doesn't feel any different in Ionic.
