### ISSUE TITLE
"same state transition are not possible" is not API-consistent with ionic's `$state.go`

### ISSUE THREAD

**Issue by jakub-g** [shprink/ionic-native-transitions#119]
https://github.com/shprink/ionic-native-transitions/blob/9192ce31215dd20b583bce126d3fff0d39e67ba4/lib/provider.js#L204

The code of `stateGo` is as follows

```
function stateGo(state = null, stateParams = {}, transitionOptions = null, stateOptions = {}) {
            if (!state) {
                $log.debug('[native transition] cannot change state without a state...');
                return;
            }
            if ($state.current.name === state){
                $log.debug('[native transition] same state transition are not possible');
                return;
            }
            unregisterToStateChangeStartEvent();
            transition(transitionOptions);
            return $timeout(() => $state.go(state, stateParams, stateOptions));
}
```

note the part where the transition is abandoned if we go to the same state

```
            if ($state.current.name === state){
                $log.debug('[native transition] same state transition are not possible');
                return;
            }
```

Due to this, we found a regression in our app, because we were doing something like this in some place:

```
$state.go(state, {}, {reload:true});
```

Right now when we do

```
$ionicNativeTransitions.stateGo(..., ..., ..., {reload:true})
```
the `$state.go` reload is not triggered.

I think for consistency, ionic-native-transitions should call `$state.go` in such case.

What do you think?

**Comment by shprink** [comment]
if `reload:true` is in Ionic's API then we need to add it too. thanks for reporting.

**Comment by jakub-g** [comment]
Cool :)

In fact it's not ionic but ui-router API: 
http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$state

> reload (v0.2.5) - {boolean=false|string|object}, If true will force transition even if no state or params have changed. It will reload the resolves and views of the current state and parent states

**Comment by jakub-g** [comment]
Hello @shprink , thanks for quickly fixing this!

Although I had a look at [this commit](https://github.com/shprink/ionic-native-transitions/pull/120/commits/a57ed70528dfb5366236cf4def23788ec5c59c62) and see that you reversed the order of parameters, I see that it was done to align with README, but it's an unnanounced backward compatible change that can break stuff for many people, so maybe you you want to change the README instead?

**Comment by shprink** [comment]
The version is now 1.0.0 with a breaking change. it is explained in the changelog https://github.com/shprink/ionic-native-transitions/blob/develop/CHANGELOG.md#100

**Comment by jakub-g** [comment]
Ok I see that you wanted to align the order of params with ionic, fine, thanks!
