### ISSUE TITLE
Current View is overlapping when i go back 

### ISSUE THREAD

**Issue by suryamuppalla** [shprink/ionic-native-transitions#121]
Hi,

When i added Your plugin with default code

But after adding this plugin the Current view is overlapping. Means current view is showing 1 or 2 Secs.

Its appearing for only in Android, In IOS its perfect

Kindly fix this issue. 

Thanks.

**Comment by zemax2468** [comment]
Hi, 

I have the same issue in my app (all options to default and no crosswalk cordova).

Here is a video (I slowed it down a bit): https://www.youtube.com/watch?v=0vi9RCsRgs8

**Comment by shprink** [comment]
can you guys share your app with me please so I could test? my email is display in my profile. thanks

**Comment by dhirajb1989** [comment]
Even I am facing the same issue. I am using cordova. This issue is only seen in android and not on ios.

**Comment by zemax2468** [comment]
sorry on my side I can not share the app due to privacy policy. If I have time, I will try to create a small app a reproduce the issue. 
After few investigations, it seems that more images the previous page has, more we see the issue... Something weird is that on:
- Nexus 4 (Android 5) => no issue
- LG G3, Samsung Galaxy S6, Nexus 6 (all on Android 6) => issue is here
- HTC M8 (Android 5) => issue is here too

**Comment by pallaviMN** [comment]
@suryamuppalla @shprink @dhirajb1989 @zemax2468 , Me too facing same issue in Samsung Galaxy Core prime. Please let me know if any solution is available. Used below code 

  $ionicNativeTransitionsProvider.setDefaultOptions({
                duration: 1000, // in milliseconds (ms), default 400,
                slowdownfactor: 4, // overlap views (higher number is more) or no overlap (1), default 4
                iosdelay: -1, // ms to wait for the iOS webview to update before animation kicks in, default -1
                androiddelay: -1, // same as above but for Android, default -1
                winphonedelay: -1, // same as above but for Windows Phone, default -1,
                fixedPixelsTop: 0, // the number of pixels of your fixed header, default 0 (iOS and Android)
                fixedPixelsBottom: 0, // the number of pixels of your fixed footer (f.i. a tab bar), default 0 (iOS and Android)
                triggerTransitionEvent: '$ionicView.afterEnter', // internal ionic-native-transitions option
                backInOppositeDirection: true // Takes over default back transition and state back transition to use the opposite direction transition to go back
            });

**Comment by riterrani** [comment]
Hi, I have the same problem. Here is my config

```
$ionicNativeTransitionsProvider.setDefaultOptions({
        duration: 200, // in milliseconds (ms), default 400,
        slowdownfactor: 8, // overlap views (higher number is more) or no overlap (1), default 4
        iosdelay: -1, // ms to wait for the iOS webview to update before animation kicks in, default -1
        androiddelay: -1, // same as above but for Android, default -1
        winphonedelay: -1, // same as above but for Windows Phone, default -1,
        fixedPixelsTop: 0, // the number of pixels of your fixed header, default 0 (iOS and Android)
        fixedPixelsBottom: 0, // the number of pixels of your fixed footer (f.i. a tab bar), default 0 (iOS and Android)
        triggerTransitionEvent: '$ionicView.enter', // internal ionic-native-transitions option
    });

    $ionicNativeTransitionsProvider.setDefaultTransition({
        type: 'slide',
        direction: 'left'
    });

```

**Comment by nicktee89** [comment]
Is there any solution?

**Comment by heekinho** [comment]
+1
The same here! Any solution?

**Comment by shprink** [comment]
@kenmickles
