### ISSUE TITLE
Transition direction is wrong when using native-ui-sref

### ISSUE THREAD

**Issue by rockchan123** [shprink/ionic-native-transitions#123]
It is fine when using href="app.main.xxx" for navigation. (direction is left)
But it is wrongly performing backward transition (direction is right) when using native-ui-sref="app.main.xxx({})" native-options="{type: 'slide', direction: 'left'}"

After investigation, it is found that problem is caused the bug on ionic-native-transition.js line 711:
$ionicNativeTransitions.stateGo(ref.state, params, **nativeOptions**, **stateOptions**);
The order of the parameter is invalid. The correct one should be $ionicNativeTransitions.stateGo(ref.state, params, **stateOptions**, **nativeOptions**);

**Comment by shprink** [comment]
yes you are right, do you mind creating a PR, I will merge and release 1.0.1 right after it. thanks very much

**Comment by shprink** [comment]
1.0.1 released with a fix for this

**Comment by rockchan123** [comment]
Oh I made a mistake. Just fork the project and found that you fixed for
this. Thanks.

2016-07-21 22:07 GMT+08:00 Julien Renaux <notifications@github.com>:
