### ISSUE TITLE
The view repeat itself before the effect change and -1 effect crash the app

### ISSUE THREAD

**Issue by houssem-yahiaoui** [shprink/ionic-native-transitions#125]
Hello, 

1 - I'm using the plugins but the effect I'm having is a very weird one.
**Scenario :** 
view1 transit to view2 - transition : slide left.
**Result :** 
View1 slide instead of View2 then view2 shows up.

her's the configuration : 

``` javascript
$ionicNativeTransitionsProvider.setDefaultOptions({
      duration: 400, // in milliseconds (ms), default 400,
      slowdownfactor: 4, // overlap views (higher number is more) or no overlap (1), default 4
      androiddelay: 10, // same as above but for Android, default -1
      fixedPixelsTop: 0, // the number of pixels of your fixed header, default 0 (iOS and Android)
      fixedPixelsBottom: 0, // the number of pixels of your fixed footer (f.i. a tab bar), default 0 (iOS and Android)
      triggerTransitionEvent: '$ionicView.afterEnter', // internal ionic-native-transitions option
      backInOppositeDirection: true // Takes over default back transition and state back transition to use the opposite direction transition to go back
    });
```

2 -Whenever I apply the -1 androiddelay option, the app just crashes on Android, is there any fix for that? Knowing my app have the latest version of the plugin from Telerik.

Thankx in advance.

**Comment by shprink** [comment]
`-1` is a valid value. Maybe you should create a ticket on the Telerik plugin repo.

As for your first question, I guess it is linked to the second. Using `-1` waits till the 2nd view loads then transition to it. What about if you set the `androiddelay` to something like 500 or 1000 ?

**Comment by menshinobi** [comment]
I also have the same problem. I have all of the default settings from the plugin and then when I transition to view 2, I saw view 2 and then view 2 slide.

**Comment by noveltys** [comment]
Exactly the same problem for me on ios device. But works fine on Android device...

**Comment by chidionuekwusi** [comment]
same problem here

**Comment by fccoelho7** [comment]
Any solution?

**Comment by houruicheng** [comment]
have the same problem here

**Comment by houruicheng** [comment]
set the androiddelay to something like 500 or 1000  will be two switching animation

**Comment by tverilytt** [comment]
Hi!
I have had the same problem (on IOS). After updating to latest version, 1.0.3, things seem to be working well, but only the first time doing a swipe. On next swipes, the behaviour is the same as before, the view repeats itself...

Anyone else experienced this?!

Cheers
-jo
