### ISSUE TITLE
Fade animation won't fire on iOS

### ISSUE THREAD

**Issue by greenyossi** [shprink/ionic-native-transitions#131]
Hi,

In my app I use the fade animation when logging in:
$ionicNativeTransitions.stateGo('dashboard',{},{},{
type:"fade",
androiddelay: -1
});

On the first transition it works fine but when logging out and trying to login the second time the app freezes. The snapshot is taken and the view changes but the animation isn't fired and the app seems frozen.

Tried to add "iosdelay: -1" and calling window.plugins.nativepagetransitions.executePendingTransition()
But it won't work.

The issue occurred also in Android but calling window.plugins.nativepagetransitions.executePendingTransition() fixed it.

I'll appreciate any help on this,
Thanks!

**Comment by shprink** [comment]
It should work, try using the cordova plugin api http://plugins.telerik.com/cordova/plugin/native-page-transitions and let us know

**Comment by greenyossi** [comment]
Hi, thanks for the quick answer.

Unfortunately it still won't work. when I try to do the fade animation for the second time it won't fire.

**Comment by greenyossi** [comment]
Can you be more specific if there are certain definitions that I need to change?

I tried to call the fade with $ionicNativeTransitions.stateGo('dashboard',{},{},{
type:"fade",
"duration"       :  600, 
  "iosdelay"       :   50,
  "androiddelay"   :  100
});

or with the plugin fade function itself:
var options = {
  "duration"       :  600, 
  "iosdelay"       :   50,
  "androiddelay"   :  100
};
window.plugins.nativepagetransitions.fade(
  options,
  function (msg) {$state.go('dashboard')}
);

but in both cases it works only the first time.
