### ISSUE TITLE
Back to previous page transition is flickering 

### ISSUE THREAD

**Issue by rajeshworkz** [shprink/ionic-native-transitions#133]

**Comment by fccoelho7** [comment]
Same here.
@shprink any solution?

**Comment by shprink** [comment]
It is written everywhere that this repo is unmaintained. I am sorry, do not
have the time to investigate.

**Comment by johnnynode** [comment]
It's a serious user experience problem !

**Comment by fccoelho7** [comment]
Fuck you Ionic! I'm gonna to React Native

Em 07/11/2016 07:33, "Ny" <notifications@github.com> escreveu:

**Comment by revolunet** [comment]
Wow.  is `fuck you` really necessary here @fccoelho7 ?

You can use whatever you want but please, please, dont insult open source volunteers ! We all have our own priorities.

**Comment by fccoelho7** [comment]
I'm sorry. Its not my intention. I'm very frustrated with Ionic. :/

Em 07/11/2016 11:51, "Julien Bouquillon" <notifications@github.com>
escreveu:

**Comment by revolunet** [comment]
Yes, as we are too with many open source projects... Have a KitKat :)

**Comment by deliverymanager** [comment]
Remove the plugin from your project.
It does not have anything to do with ionic.

Στις 7 Νοε 2016 16:04, ο χρήστης "Julien Bouquillon" <
notifications@github.com> έγραψε:

**Comment by srameshr** [comment]
@fccoelho7 Totally understand your frustration. Would totally encourage you to move to React-Native without even thinking about Ionic 2 or 1  or any other web view mobile UI frameworks. Just be polite. It does not hurt.
