### ISSUE TITLE
iOS flash before transition

### ISSUE THREAD

**Issue by Stylemayster** [shprink/ionic-native-transitions#14]
I don't know if it come from you plugin or telerik, but when I do a slide transition on iOS, it flash white juste before starting sliding when slide left with delay set to -1. slide right seem to be ok.

I've also revert direction, default transition slide right instead of left and default back transition to left instead of right (just in case it was my code), believe me, slide left flicker again (even if it just go back) and slide right is perfect.
$ionicNativeTransitionsProvider.setDefaultTransition({
	type: 'slide',
	direction: 'right'
});
$ionicNativeTransitionsProvider.setDefaultBackTransition({
	type: 'slide',
	direction: 'left'
});

Tell me I'm not alone to encounter this issue ^^'

**Comment by shprink** [comment]
try in the console to past that and let me know if it is the same:

```
window.plugins.nativepagetransitions.slide({
direction: 'left'
});
```
then
 
```
window.plugins.nativepagetransitions.executePendingTransition();
```

**Comment by Stylemayster** [comment]
No flash occured with your technique (nice technique by the way ^^).

**Comment by Stylemayster** [comment]
The flash also occur with the iOS emulator.

**Comment by Stylemayster** [comment]
Aaah men, I've just noticed a this moment that the glitch is not a white flash but a brief apparition of the screenshot of the next page. I don't know if it change something...

**Comment by shprink** [comment]
You have -1 on both ios and android delay right?

**Comment by Stylemayster** [comment]
Yes. Here is my config :
$ionicNativeTransitionsProvider.setDefaultOptions({
	duration: 400, // in milliseconds (ms), default 400,
	slowdownfactor: 4, // overlap views (higher number is more) or no overlap (1), default 4
	iosdelay: -1, // ms to wait for the iOS webview to update before animation kicks in, default -1
	androiddelay: -1, // same as above but for Android, default -1
	winphonedelay: 200, // same as above but for Windows Phone, default -1,
	fixedPixelsTop: 0, // the number of pixels of your fixed header, default 0 (iOS and Android)
	fixedPixelsBottom: 0, // the number of pixels of your fixed footer (f.i. a tab bar), default 0 (iOS and Android)
	triggerTransitionEvent: '$ionicView.afterEnter' // internal ionic-native-transitions option
});
$ionicNativeTransitionsProvider.setDefaultTransition({
	type: 'slide',
	direction: 'left'
});
$ionicNativeTransitionsProvider.setDefaultBackTransition({
	type: 'slide',
	direction: 'right'
});


Just for fun, I've also tested with setDefaultTransition -> direction:up  and   setDefaultBackTransition-> direction : down.
The glitch occur for direction left and up.

**Comment by willianbs** [comment]
@Stylemayster Here's my config, working without glitch (telerik 0.5.0 and beta6 of this plugin):

```javascript
$ionicNativeTransitionsProvider.setDefaultOptions({
            "duration": 200, // in milliseconds (ms), default 400,
            "slowdownfactor": 4, // overlap views (higher number is more) or no overlap (1), default 4
            "iosdelay": 60, // ms to wait for the iOS webview to update before animation kicks in, default -1
            "androiddelay": 70, // same as above but for Android, default -1
            "winphonedelay": 200, // same as above but for Windows Phone, default -1,
            "fixedPixelsTop": 0, // the number of pixels of your fixed header, default 0 (iOS and Android)
            "fixedPixelsBottom": 54, // the number of pixels of your fixed footer (f.i. a tab bar), default 0 (iOS and Android)
            "triggerTransitionEvent": '$ionicView.afterEnter' // internal ionic-native-transitions option
        });
```

I use tabs navigation so my fixedPixelsBottom is 54.

**Comment by shprink** [comment]
try installing https://github.com/Telerik-Verified-Plugins/WKWebView it
should fix your problems

**Comment by Stylemayster** [comment]
@shprink  You're right. It stop flashing after I've installed the plugin. Thx!!

**Comment by Stylemayster** [comment]
Finally, it was a bug from telerik plugin. @EddyVerbruggen resolve it now. (without needing of wkwebview plugin)
