### ISSUE TITLE
Problem with crosswalk webview

### ISSUE THREAD

**Issue by go2hyder** [shprink/ionic-native-transitions#15]
App crashes(shows alert message 'unfortunately application has stopped) with crosswalk web view.
(works fine without crosswalk plugin).

Thank U

**Comment by shprink** [comment]
What version of telerik's plugin? Can you try with 0.5.1 ? https://github.com/Telerik-Verified-Plugins/NativePageTransitions/tree/0.5.1

**Comment by shprink** [comment]
Actually you can follow this thread: https://github.com/Telerik-Verified-Plugins/NativePageTransitions/issues/79

**Comment by go2hyder** [comment]
Yes.I have installed telerik's plugin 0.5.1.


Thank U

**Comment by shprink** [comment]
All fixed in 0.5.4.
