### ISSUE TITLE
Back button with custom ng click wont listen to setDefaultBackTransition

### ISSUE THREAD

**Issue by raymatos** [shprink/ionic-native-transitions#19]
i have the following

```
<ion-nav-bar class="bar-stable" ng-controller="MainController">
        <ion-nav-back-button native-back class="button-clear ion-chevron-left" ng-click="mainGoBack()">&nbsp;Back</ion-nav-back-button>
    </ion-nav-bar>
```

```
$ionicNativeTransitionsProvider.setDefaultTransition({
        type: 'slide',
        direction: 'left'
    });

    $ionicNativeTransitionsProvider.setDefaultBackTransition({
        type: 'slide',
        direction: 'right'
    });
```

Clicking on the back button will still animate to the left and not right

**Comment by shprink** [comment]
Yes that is correct. Why do you have a custom ng-click on the ion-nav-back-button directive?

What the project does is that it overwrite the `$rootScope.$ionicGoBack` function: https://github.com/shprink/ionic-native-transitions/blob/develop/lib/run.js#L23

When no ng-click is defined the ion-nav-back-button directive adds it with `$rootScope.$ionicGoBack` call that is why it work if you do not have ng-click defined.

**Comment by raymatos** [comment]
Ionic tabs have there own history, for my use case I need the history to flow from one tab to another.  So I am using my own back function.  




How can i add the animation to my function?



—

**Comment by raymatos** [comment]
Can I just add this?





 $ionicNativeTransitions.transition('back');




—

**Comment by shprink** [comment]
Try that and let me know ;)

**Comment by shprink** [comment]
```
$ionicNativeTransitions.unregisterToStateChangeStartEvent();
$ionicNativeTransitions.transition('back');
```

**Comment by raymatos** [comment]
That works thanks.

Is there any way to control the animation for the header?  Seems like its fading in and out.

**Comment by shprink** [comment]
For tabs I suggest to disable animations but you could also try `fixedPixelsTop` and `fixedPixelsBottom` options.


```
$ionicNativeTransitionsProvider.setDefaultOptions({
        duration: 400, // in milliseconds (ms), default 400,
        slowdownfactor: 4, // overlap views (higher number is more) or no overlap (1), default 4
        iosdelay: -1, // ms to wait for the iOS webview to update before animation kicks in, default -1
        androiddelay: -1, // same as above but for Android, default -1
        winphonedelay: -1, // same as above but for Windows Phone, default -1,
        fixedPixelsTop: 0, // the number of pixels of your fixed header, default 0 (iOS and Android)
        fixedPixelsBottom: 0 // the number of pixels of your fixed footer (f.i. a tab bar), default 0 (iOS and Android)
        triggerTransitionEvent: '$ionicView.afterEnter' // internal ionic-native-transitions option
    });
```
