### ISSUE TITLE
Can't set anroiddelay

### ISSUE THREAD

**Issue by DmitrySkripkin** [shprink/ionic-native-transitions#20]
I use beta6 version with Telerik plugin 0.53 (tried other versions too). Default transitions are set correctly (checked other types of animation), but transition starts immediately in any case. Tested on android 5.1 devices and 4.2.

```javascript
.config(function($ionicNativeTransitionsProvider){
    $ionicNativeTransitionsProvider.setDefaultTransition({
      type: 'slide',
      direction: 'left'
    });
    $ionicNativeTransitionsProvider.setDefaultBackTransition({
      type: 'slide',
      direction: 'right'
    });
    $ionicNativeTransitionsProvider.setDefaultOptions({
      androiddelay: 3000
    });
})
```

**Comment by shprink** [comment]
You are right. This is related to this issue: https://github.com/Telerik-Verified-Plugins/NativePageTransitions/issues/79

**Comment by DmitrySkripkin** [comment]
Was not sure about it. Thanks, will wait for new plugin version.

**Comment by shprink** [comment]
Closing, 0.5.4 has been released. It fixes this problem!
