### ISSUE TITLE
Enable/Disable as a service

### ISSUE THREAD

**Issue by hlehmann** [shprink/ionic-native-transitions#22]
Is it possible to use Enable/Disable in a service instead of a provider ?

**Comment by shprink** [comment]
The answer is no.

What is the use case?

**Comment by hlehmann** [comment]
Well in most some situations the default behaviour is good but some times I expect another animation so I want to temporary disable the native transition. 
I did it by saving the enable function of the provider in a global variable.

    nativeTransitionEnable(false)
    $state.go(...)
    nativeTransitionEnable(true)

More generally it could be interesting to set a `nextTransition` function like `nextTransition({type: 'fade'})` or `nextTransition(null)` to have a temporary configuration depending on the source or the context.

**Comment by shprink** [comment]
Good, This is interesting, will add public methods to do that
