### ISSUE TITLE
Ionic view lifecycle event fired inaccurately

### ISSUE THREAD

**Issue by NgYueHong** [shprink/ionic-native-transitions#23]
When Ionic page transition animation is disabled via `$ionicConfigProvider.views.transition('none')`, the view event like `$ionicView.afterEnter` will not executes accurately. You can clearly see the problem when you test on low end budget device. This brings the problem of same page being animate in, even if you try to animate it with `afterLeave`.

I have report the issue to ionic (https://github.com/driftyco/ionic/issues/4555), but I don't hope to see any action taken for it soon. So, for now the only way is to avoid disable animation using `$ionicConfigProvider.views.transition('none')`.  The downside is we will have a small delay on page transition that we need to wait for ionic animation to finish, only then animate ours. Or you have any idea of alternative way to disable ionic animation or speed up the animation to make it extreme fast like almost no transition?

**Comment by NgYueHong** [comment]
I found that we can have accurate ionic view event with no animation by using `nav-transition="none"`. Please see how this can be implemented into your plugin. Thank you.

**Comment by shprink** [comment]
Thanks for the research. I will check if I can add this directive during
config time.

**Comment by shprink** [comment]
Do you mean this: http://ionicframework.com/docs/api/directive/navTransition/ ?

If so I do not think this plugin can do anything about it except adding this to the documentation. What do you think?

**Comment by NgYueHong** [comment]
@shprink Yeah, I am referring to that. If that can't be done, then adding to the documentation would be fine. However, I guess you may need to remove `$ionicConfig.views.transition('none')` from your code. Otherwise, people will need to manually remove it from your code or add `$ionicConfig.views.transition('platform')` on their code to override yours to avoid the problem.

**Comment by shprink** [comment]
You can now disable/enable ionic transitions using:

https://github.com/shprink/ionic-native-transitions/blob/develop/README.md#enabledisable-optional

**Comment by NgYueHong** [comment]
@shprink That's awesome!!!! Didn't notice it is implemented.

**Comment by shprink** [comment]
I am listening to you bro :)
