### ISSUE TITLE
Disabling Transitions for Certain Links

### ISSUE THREAD

**Issue by gregavola** [shprink/ionic-native-transitions#26]
Hey there,

Love this plugin, but for tabs - there isn't an need for native Transitions - so is there a way to disable transitions for certain links, but enabling it for everything?

Also - for Swipe back, is there a way to simply disable the Native Transition and go back to the old Ionic swipe back?

**Comment by shprink** [comment]
You can disable transitions for any state you want.

```
.state('home', {
    url: '/home',
    nativeTransitions: null,
    templateUrl: "templates/home.html"
})
```

https://github.com/shprink/ionic-native-transitions#usage

For slide back, for now it just uses default transition, not the back transition. For now it will stay like that https://github.com/shprink/ionic-native-transitions#swipe-back-ios

**Comment by gregavola** [comment]
Is there a way to set this as a directive since these are tabs - and we don't specifically set the stage.go.

I realize about the swipe back - per the documentation - but was asking specifically about just disabling native transitions for swipe back and defaulting to the ionic transactions. It seems to use native transitions.

**Comment by shprink** [comment]
Are you saying your tabs do not have states defined? If it is the case then you should consider adding them.

You could also disable transitions from your controller:

```
$ionicNativeTransitions.enable(false);
```

No way to default swipe back transition to ionic for now.

**Comment by shprink** [comment]
See how to remove transitions for tabs: https://github.com/shprink/ionic-native-transitions/blob/develop/test/config.js#L22-L35

**Comment by gregavola** [comment]
They are already disabled for tabs - that's how the framework works. However - when using this plugin - it enables transitions on tab actions. I will try the disabling the transitions in the tabscontroller and see if that helps.

Greg

**Comment by shprink** [comment]
THe link I just shared is a example on how to disable native transitions for tabs. It works, do the same

**Comment by gregavola** [comment]
What options can be set here - anything about the top and bottom offset?

Greg

**Comment by gregavola** [comment]
Got it - thank you.

Greg

**Comment by shprink** [comment]
Glad I could help :) Enjoy the plugin. If you have any requests or problems with 1.0.0-rc1 please add a comment on #25

**Comment by gregavola** [comment]
Hey Julien,

One more quick questions - the "swipe back" is awkward with native
transitions (the header moves, but the body does not) - can this be
"temporarily removed" somehow to default back to ionic navigation?

Greg

On Sun, Nov 8, 2015 at 11:39 PM, Julien Renaux <notifications@github.com>
wrote:

> Glad I could help :) Enjoy the plugin. If you have any requests or
> problems with 1.0.0-rc1 please add a comment on #25
> <https://github.com/shprink/ionic-native-transitions/issues/25>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shprink/ionic-native-transitions/issues/26#issuecomment-154919475>
> .
>



-- 
Greg Avola
http://gregavola.me
(c) 508.596.8811

**Comment by shprink** [comment]
Do you know if there is any event I could listen to? Last time I checked there was no way to intercept swipe back event and prevent the native transition from happening. What you can do is disable swipe back I guess

**Comment by gregavola** [comment]
Either way, when does the transition fire? Before the plugin, it would move
the entire `ion-view` over the page (if you moved it slowly), but here - it
just moves the header and nothing else. It actually doesn't even move back
in the page.

Greg

On Mon, Nov 9, 2015 at 10:11 AM, Julien Renaux <notifications@github.com>
wrote:

> Do you know if there is any event I could listen to? Last time I checked
> there was no way to intercept swipe back event and prevent the native
> transition from happening. What you can do is disable swipe back I guess
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shprink/ionic-native-transitions/issues/26#issuecomment-155091532>
> .
>



-- 
Greg Avola
http://gregavola.me
(c) 508.596.8811

**Comment by shprink** [comment]
Ok that's a bug then. I will try thanks

**Comment by gregavola** [comment]
You could also listen for swipe-back ionGesture. This is the only thing
that is limited me from releasing the app. Anything I can do to help?

Greg

On Mon, Nov 9, 2015 at 10:34 AM, Julien Renaux <notifications@github.com>
wrote:

> Ok that's a bug then. I will try thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shprink/ionic-native-transitions/issues/26#issuecomment-155097636>
> .
>



-- 
Greg Avola
http://gregavola.me
(c) 508.596.8811

**Comment by shprink** [comment]
`$ionicConfigProvider.views.swipeBackEnabled(false);` for now.

**Comment by gregavola** [comment]
An update on this bug?

Greg

**Comment by shprink** [comment]
Nope. I'll tackle that at the same time as #27 and #28
