### ISSUE TITLE
Auto opposite back transition

### ISSUE THREAD

**Issue by shprink** [shprink/ionic-native-transitions#27]
For example if this is the series of animation I go through when enter to next page:
slide right, slide right, slide up, fade in

Then, if now I continuously hit the back button, it would be:
fade out, slide down, slide left, slide left

From #25

**Comment by numerized** [comment]
+1

**Comment by shprink** [comment]
Rc3

**Comment by shprink** [comment]
```
$ionicNativeTransitionsProvider.setDefaultOptions({
        backInOppositeDirection: true
});
```
