### ISSUE TITLE
I get inject module error when I try to configure angular module

### ISSUE THREAD

**Issue by wayshall** [shprink/ionic-native-transitions#29]
Hi all !
I install this ionic-native-transitions plugin to my inoic project,
but I get inject module error when I try to configure angular module:
Error: [$injector:nomod] Module 'ionic-native-transitions' is not available! You either misspelled the module name or forgot to load it.

configuration code:
angular.module('houseApp', ['ionic-native-transitions']);

can anyone help me?

**Comment by shprink** [comment]
You need to include the dist script to your page. If you use commonjs a
simple require would do. If not include de script tag with the plugin path
in your page

**Comment by wayshall** [comment]
@shprink thanks!
I have got off work, so I can't try it now.
I will try it tomorrow.
But I wonder that why I have to include the script into page?
I use ionic plugin command to install it, and it was installed as plugin,
Isn't it does not auto load?
And the other plugin which I had installed are not need to include the script file

**Comment by shprink** [comment]
This plugin is not a Cordova plugin. It is a wrapper around it, you need to include the dist file the same way you need to include NgCordova to your application.

**Comment by wayshall** [comment]
@shprink thanks very much!

**Comment by numerized** [comment]
and you need to input the cordova.js file in your index.html file
I was struggling to find my mistake...

<script src="cordova.js"></script>

**Comment by jeffthompson1971** [comment]
I have the same issue.   It works out of the box for IOS if I install via bower, but building for android fails the build.   When I use the ionic CLI approach to install the plugin it works, but I get this same module missing error.   But when you say 'include the dist' what does that mean?  where do i find it?  how do i include it.  can you please give more details than just 'include the dist script to your page'?    I'm new and not following what to do there.  I go to the plugin itself and i see no 'dist' directory at all:

bash-3.2$ pwd
/Users/thompjg/workspace/3BD-APPS/3bd-snaplistings/plugins/com.telerik.plugins.nativepagetransitions
bash-3.2$ ls
README.md	adapters	demo		package.json	plugin.xml	src		www
bash-3.2$ find . | grep dist
bash-3.2$

any specifics would be very helpful.

**Comment by shprink** [comment]
```
<script src="PathToBower/ionic-native-transitions/dist/ionic-native-transitions.js">
```

that's what I meant by "include the dist"

**Comment by stefanotauriello** [comment]
I have installed using both Cordova and Ionic CLI but when i add 'ionic-native-transitions' in angular.module, it doesn't find the module.

How can I resolve this?

Thanks

**Comment by shprink** [comment]
You need to include the lib in your app. See previous messages.

**Comment by stefanotauriello** [comment]
If I include js file Inreceive error: Cordova is not defined

Il mercoledì 4 maggio 2016, Julien Renaux <notifications@github.com> ha
scritto:

> You need to include the lib in your app. See previous messages.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/shprink/ionic-native-transitions/issues/29#issuecomment-216836045>
>


-- 
Tauriello Stefano
Ingegnere W.I.N. Spa

**Comment by shprink** [comment]
You also need to include cordova in a cordova app ;)

**Comment by stefanotauriello** [comment]
My app is a Ionic app, and during development Cordova.js is not necessary,
isn't it?

Il mercoledì 4 maggio 2016, Julien Renaux <notifications@github.com> ha
scritto:

> You also need to include cordova in a cordova app ;)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/shprink/ionic-native-transitions/issues/29#issuecomment-216836485>
>


-- 
Tauriello Stefano
Ingegnere W.I.N. Spa

**Comment by shprink** [comment]
Cordova.js is necessary while on device.

**Comment by cotufaloschiflones** [comment]
@stefanotauriello @wayshall @shprink 
I had the same problem. It's very important to know if you are using a scaffolding tool (I use the generator-ionic-gulp). Recently they changed "the way" of the compiling process, see this link (point 2).
https://www.npmjs.com/package/generator-ionic-gulp#development-mode

Previously the export of the final vendor.js file (with all the dependencies) came from vendor.json and now it came from bower.json. So in order to work properly you must to update that file :)
