### ISSUE TITLE
Animate too early or too late

### ISSUE THREAD

**Issue by NgYueHong** [shprink/ionic-native-transitions#3]
When using native transition, I always face the following issue:
- Different page content will have different load time
- Different model of smartphone will have different load time based on it's performance
- Background running app on user device may cause unexpected slow load of a page causing improper transition animation (animate too early)

Therefore, it is the trouble of animation to be animated too early (where same page slide in, only then change to next page). Or, animated too late (the delay is properly set for low end device, but it will be too slow for high end performance device).

It would be great & super cool if your plugin can help to avoid or reduce this issue.

**Comment by shprink** [comment]
HI,

You can disabled the plugin for old device if needed:

```
if (somewayToCheckIfOldDevice){
    $ionicNativeTransitionsProvider.enable(false);
}
```

If what you say is right (different device = different load time) then I do not know what to do about it. Any ideas?

**Comment by NgYueHong** [comment]
if (somewayToCheckIfOldDevice){

How to check for old device? In stead of saying old device, new budget device will also have slow performance.

Yeah, that is for sure (different device = different load time). Even different page content will have different load time.

Maybe can try with ionic lifecycle? (http://www.gajotres.net/understanding-ionic-view-lifecycle/)
Or, a fork of NativePageTransitions to modify it to have a control when to take the first screenshot, and second screenshot & animate it via API?

**Comment by NgYueHong** [comment]
@shprink Check this out: https://github.com/Telerik-Verified-Plugins/NativePageTransitions/issues/62#issuecomment-147905901

Maybe you see how to implement it with your plugin. :)

**Comment by shprink** [comment]
Awesome @NgYueHong ! Will try it out asap

**Comment by shprink** [comment]
Included in beta3

**Comment by NgYueHong** [comment]
Tried with your new update. But the animation is occurring too early. I am testing on very low end android device (ZTE V815W) and I can see the same page animate in on almost every page transition (using the ionic default sidemenu template). Try to animate after `$ionicView.afterLeave` instead of `$stateChangeSuccess` to ensure the new page is properly loaded before animation started across all devices. The `$stateChangeSuccess` is fired even earlier than `$ionicView.loaded`.

**Comment by shprink** [comment]
Thanks for sharing, I will try and update :)

**Comment by NgYueHong** [comment]
I just saw your new beta4 update, but haven't test it. I guess it should solve same page transition in issue with the simple example app on my test. 

But I think adding `pendingTransitionDelay` to it isn't very reliable solution to solve the problem. Because the original problem is different page will have different load time between `$stateChangeSuccess` to '$ionicView.afterEnter'.  Something that is not on our control. In other words, using `pendingTransitionDelay` will have no different than using `androiddelay` to delay the transition and it does not actually solve the problem.

**Comment by shprink** [comment]
Check beta5 out. I use $ionicView.afterEnter event but you can change it
via the default config.

Let me know if it works on your end. On android the plugin is unstable but
on iOS it works fine.
