### ISSUE TITLE
pass backgroundColor to flip

### ISSUE THREAD

**Issue by tbro028** [shprink/ionic-native-transitions#31]
Hi,
Trying to pass background color to flip transition https://github.com/Telerik-Verified-Plugins/NativePageTransitions/issues/84

I set default options:
$ionicNativeTransitionsProvider.setDefaultOptions({
		       'backgroundColor' : "#585F5F"
            });

but log is showing it is not passed in to transition:

 [native transition]{"direction":"left"}

**Comment by shprink** [comment]
this log on logs the transition passed not the merge between defaultOptions and transition.

Do you use the right version of telerik's plugin (0.5.4-dev)?

**Comment by tbro028** [comment]
I'm using 0.5.4 which i'd assumed was the release of the dev version. Is
that wrong? pgb won't let me use 0.5.4-dev

**Comment by shprink** [comment]
maybe.

Use the background color in a transition not in the defaultOptions.

**Comment by tbro028** [comment]
thanks, passing it directing in works.
