### ISSUE TITLE
Using from $state.go()

### ISSUE THREAD

**Issue by vandervidi** [shprink/ionic-native-transitions#33]
Is it possible to use the transitions from the $state.go() method?
In case its possible, can you add an example?

**Comment by shprink** [comment]
https://github.com/shprink/ionic-native-transitions#state

;)

**Comment by vandervidi** [comment]
This is not i meant.
I would like to add dynamic transitions in $state.go(), for example in a controller.

**Comment by shprink** [comment]
that's exactly what this is for:

```
$ionicNativeTransitions.stateGo('yourState', {}, {
    "type": "slide",
    "direction": "up", // 'left|right|up|down', default 'left' (which is like 'next')
    "duration": 1500, // in milliseconds (ms), default 400
});
```

it transition to the new state with a native transition of your choice.

**Comment by vandervidi** [comment]
cool, thanks!
BTW, this is an awesome project! nice work
