### ISSUE TITLE
Transition works just one time on device

### ISSUE THREAD

**Issue by candelibas** [shprink/ionic-native-transitions#34]
When I add nativeTransitions in routes like this;

nativeTransitions: {
        "type": "slide",
        "direction": "left"
    },

It works just one time on Android device

**Comment by shprink** [comment]
all of this cases https://github.com/shprink/ionic-native-transitions/blob/develop/test/config.js#L21-L76 works fine on my end using Crosswalk and iOS.

Using this only add the transition to a state. if you want to define a transition for all page you should use the provider https://github.com/shprink/ionic-native-transitions#set-default-transition-optional

Can you tell me a bit more on the Telerik's version that you use, this plugin version and wheter or not you use crosswalk

**Comment by candelibas** [comment]
Yes, I'm using crosswalk and version of plugin is 0.5.4. 

When I define for all pages it works fine. But in states, works just one time as I said.

Now, I realized that this code doesn't work too.

$ionicNativeTransitionsProvider.setDefaultTransition({
        type: 'slide',
        direction: 'left'
    });

 But it works on flip for all pages. Did I missed something?

**Comment by shprink** [comment]
Please send me part of the code that uses this plugin (state definition and config) I will try to reproduce.

have you added this: https://github.com/shprink/ionic-native-transitions#android ?

**Comment by candelibas** [comment]
Oh, I was removed the line in config.xml I don't know why but I added it again and it perfectly works now! Thanks for quick replies!

**Comment by shprink** [comment]
Good to hear that!
