### ISSUE TITLE
Installation and configuration issue

### ISSUE THREAD

**Issue by agrawalravi95** [shprink/ionic-native-transitions#38]
Followed all the tutorials, but I keep getting the error:

"nativepagetransitions is disabled or nativepagetransitions plugin is not present"

Some help?

**Comment by shprink** [comment]
Have you correctly installed nativepagetransitions cordova's plugin if so which version?

```
cordova plugin add https://github.com/Telerik-Verified-Plugins/NativePageTransitions#0.5.5
```

**Comment by agrawalravi95** [comment]
I did. The version i installed was __0.5.4__

**Comment by shprink** [comment]
Is it working @agrawalravi95 ?

follow this maybe you have the same problem: https://github.com/shprink/ionic-native-transitions/issues/40

Do not hesitate to re-open this issue if it does not work

**Comment by annapogorelova** [comment]
Having the same issue but only on Android. The first time I run it on device window.cordova.nativepagetransitions is initialized. But the next time and further on it's undefined. Has someone experienced the same issue? I have crosswalk installed. Everything configured correctly as in guide.

**Comment by shprink** [comment]
which version of the telerik plugin do you have? 0.5.5 works

**Comment by annapogorelova** [comment]
Neither 0.5.6 nor 0.5.5 works for me.
