### ISSUE TITLE
npm install ionic-native-transitions not working

### ISSUE THREAD

**Issue by raphaelduartepinheiro** [shprink/ionic-native-transitions#4]
Hi, when I run this command ``npm install ionic-native-transitions --save`` the prompt gives me this feedback:

    npm ERR! Windows_NT 6.3.9600
    npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ionic-native-transitions" "--save"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1

I'm using Windows 10, and the installing process works with others packages.
I've been able to install using bower, but I can't understand the origin of this issue.

**Comment by shprink** [comment]
I have just tried (`npm install ionic-native-transitions --save`) and it
works on my end.

Maybe it is related to node/npm versions. Here are mine:

12:57 $ node -v
v4.1.0
12:58 $ npm -v
3.3.3

**Comment by raphaelduartepinheiro** [comment]
@shprink thank you for your reply. I'll try to update both node and npm to latest version and ASAP I'll check this issue.

**Comment by raphaelduartepinheiro** [comment]
Tested in a new ionic repository and it works normally. I think it's a problem in my old package.json.
