### ISSUE TITLE
Native Transitions doesn't load

### ISSUE THREAD

**Issue by Requiescat** [shprink/ionic-native-transitions#40]
Thanks a lot for your work! This incredible plugint seems to work well for most of the users but not for me...

1/ I've installed the lib in my project with bower install shprink/ionic-native-transitions --save
2/ Included   <script src="lib/ionic-native-transitions/dist/ionic-native-transitions.js"></script> in my index.html file
3/ Included the require in my routes.js file

=> No error on run but I see no change compare to normal transition. What am I missing??

Below is my code for routes.js

```Javascript
angular.module('app.routes', ['ionic-native-transitions'])

  .config(function ($ionicNativeTransitionsProvider, $stateProvider, $urlRouterProvider, $ionicConfigProvider) {

    // Ionic uses AngularUI Router which uses the concept of states
    // Learn more here: https://github.com/angular-ui/ui-router
    // Set up the various states which the app can be in.
    // Each state's controller can be found in controllers.js
  
    $ionicNativeTransitionsProvider.setDefaultOptions({
      duration: 500,
      // backInOppositeDirection: true
    });

    $ionicNativeTransitionsProvider.setDefaultTransition({
      type: 'flip',
      direction: 'left'
    });

    $ionicNativeTransitionsProvider.setDefaultBackTransition({
      type: 'slide',
      direction: 'right'
    });

    $ionicNativeTransitionsProvider.enable(true);

    $ionicConfigProvider.tabs.position('top');

    $stateProvider



      .state('login', {
        url: '/login ',
        nativeTransitions: null,
        templateUrl: 'templates/login.html',
        controller: 'loginCtrl'
      })


      .state('tabMenu', {
        url: '/tabMenu',
        abstract: true,
        templateUrl: 'templates/tabMenu.html'
      })


      .state('tabMenu.match', {
        url: '/match',
        views: {
          'tab10': {
            templateUrl: 'templates/match.html',
            controller: 'matchCtrl'
          }
        }
      })

**Comment by shprink** [comment]
You need to install Telerik's plugin, read the doc.

**Comment by Requiescat** [comment]
That's what I've done but I got an error on ionic serve: nativepagetransitions is disabled or nativepagetransitions plugin is not present

**Comment by shprink** [comment]
Ionic serve is within the browser right? Native transitions only happen on device.

**Comment by Requiescat** [comment]
Yes but I've tried both in fact but if I do a ionic run android -console, I can see exactly the same error. It seems the plugin is not active, I don't know why.

**Comment by shprink** [comment]
On device open the console and run `window.plugins.nativepagetransitions`. If it is not defined then the plugin is not installed properly.

**Comment by Requiescat** [comment]
Well I got TypeError: Cannot read property 'nativepagetransitions' of undefined.
I've tried to reinstall the plugin several times but still not working so I'lle start from a blank project an let you know.

**Comment by shprink** [comment]
Do you have `cordova.js` correclty injected into your app? If you type `cordova` in the console on device what happen?

**Comment by Requiescat** [comment]
Thanks a lot for your help, it's finally working ! Indeed something was wrongly configured with myproject plugins so I made a fresh start and was abble to load your plugin :+1: 
On my phone it's a big laggy though, I run it on a Lenovo Vibe shot so it should be ok

**Comment by Requiescat** [comment]
It's a way better with crosswalk ! This plugin is amazing and everything feels like a pure native app !

**Comment by SK-CSE** [comment]
$ionicNativeTransitionsProvider.setDefaultBackTransition({
      type: 'slide',
      direction: 'right'
    });
is not working in my case.. what to do..???

**Comment by shprink** [comment]
the only reason I could think of @SK-CSE is that you have overwritten the back button behavior such as: 

```
<ion-nav-back-button class="button-clear"
    ng-click="myGoBack()">
    <i class="ion-arrow-left-c"></i> Back
  </ion-nav-back-button>
```

instead of the default:

```
<ion-nav-back-button>
  </ion-nav-back-button>
```

**Comment by SK-CSE** [comment]
i use $ionicHistory for back naviagtion...

<ion-header-bar>
		<div class="header">
			<div   ng-click="goBack()" nav-direction="back">
				<img src="img/back-arrow.png">
			</div>			 
	  	</div>
</ion-header-bar>
*******************************************************
$scope.goBack = function(){
    $ionicHistory.goBack();
  } ;

please suggest something to achieve  desire transition with using ionic history... @shprink

**Comment by shprink** [comment]
Just use the default back button:

```
<ion-nav-back-button>
  </ion-nav-back-button>
```

There is no need for your function:

```
$scope.goBack = function(){
$ionicHistory.goBack();
} ;
```

**Comment by SK-CSE** [comment]
ion-nav-back-button is fine but actually i have to go two view back in some cases... @shprink 
$ionicHistory.goBack(-2); 
is there any way to use setDefaultBackTransition()  with ionic history..??

**Comment by shprink** [comment]
I guess you could get the state you want to transition to using the api http://ionicframework.com/docs/api/service/$ionicHistory/

Once you get the state, you could transition manually to it using stateGo method: https://github.com/shprink/ionic-native-transitions#state

**Comment by annapogorelova** [comment]
Having the same issue. nativepagetransitions is disabled or nativepagetransitions plugin is not present. I installed it according to the guide, but it's initialized only the first time I run the app on device from fresh start (on iOS it works - having problem only with Android).
