### ISSUE TITLE
Screen stuck after $stateChangeStart is defaultPrevent'ed

### ISSUE THREAD

**Issue by Klaster1** [shprink/ionic-native-transitions#45]
Consider the following scenario:
1. User leaves the state, either by going back or to another state.
2. To confirm state change, I call `preventDefault` on $stateChangeStart event.
3. Continue state change after confirmation.

I guess there's a issue with ionic-native-transitions because after event's prevented, the screen gets stuck until `executePendingTransition` is called manually. At least this is what I get on iOS 9.1 with platform 3.9.2 and cordova-plugin-wkwebview.

**Comment by shprink** [comment]
this lib also uses `$stateChangeStart` event to trigger the transition and use the `enter` event to call `executePendingTransition`.

Do you do that for some kind of authentication checking?

**Comment by Klaster1** [comment]
I do this to confirm state exit in this particular case. Does the uirouter add eventPrevented property on the event object? If it's true, then you can maybe add additional check into transition function. This is an essential uirouter feature and your library pretty much breaks what developers describe even in official docs, which is unfortunate.

**Comment by shprink** [comment]
Can you share a link on where this is explained in the doc? I have never had to use this case before.

Thanks

**Comment by Klaster1** [comment]
https://github.com/angular-ui/ui-router/wiki#state-change-events

**Comment by shprink** [comment]
Gracias

**Comment by Klaster1** [comment]
I made a [fiddle](http://jsfiddle.net/Klaster_1/nrut6g19/1/) that demonstrates `defaultPrevented` check. Open the console and click on anchor to see the result. I propose to wrap [this function](https://github.com/shprink/ionic-native-transitions/blob/develop/lib/provider.js#L358) into `requestAnimationFrame` and add additional check `if (e.defaultPrevented) return` after or before [this line](https://github.com/shprink/ionic-native-transitions/blob/develop/lib/provider.js#L361). Not sure if one frame delay won't break anything, though.

**Comment by shprink** [comment]
Awesome, thanks very much.

Why not just do:

```
if (e.defaultPrevented) return
```
?

What would be the purpose of requestAnimationFrame? also `requestAnimationFrame` is not cross browser.

**Comment by Klaster1** [comment]
The check has to be run in async wrapper to eliminate race condition. If you don't, then you'll check for prevention before other listener has prevented the $stateChangeStart, which beats the purpose.

**Comment by Klaster1** [comment]
After some fiddling with `requestAnimationFrame` wrapper for a while it doesn't seem like a good idea because transitions tend to randomly break. I left the `preventDefault` check though, since it does what I wanted, but in a roundabout way: you need to catch and cancel the event with listener that fires before ionic-native-transition's `$stateChangeStart` listener. This can be achieved by simply registering it earlier or, if listener is created in controller, manually changing the order of `$rootScope.$$listeners.$stateChangeStart`.

**Comment by shprink** [comment]
that's great, do you mind sending a PR?

Thanks very much!
