### ISSUE TITLE
Ionic side menu with native transitions

### ISSUE THREAD

**Issue by jdnichollsc** [shprink/ionic-native-transitions#46]
Hi man, please test the transition with the side menu... Is neccesary first close the menu and after make the transition.

Thanks in advance

**Comment by shprink** [comment]
What's your question?

**Comment by jdnichollsc** [comment]
The transition start before close the side menu

**Comment by oudj001** [comment]
Anyone have an solution for this, instead of programmatically close the menu and then do the transition? Thanks in advance!

**Comment by leonardobazico** [comment]
+1

**Comment by rajnandan1** [comment]
+1

**Comment by thgfrzm** [comment]
This issue can be properly seen if the property fixedPixelsTop value > 0.

**Comment by Kratos-SA** [comment]
+1

**Comment by Kratos-SA** [comment]
did you guys come up with a work around?

**Comment by jibinbs** [comment]
+1

**Comment by jibinbs** [comment]
please guys find a solution for this problem.otherwise this native transition is great
