### ISSUE TITLE
Integration with side menu

### ISSUE THREAD

**Issue by raphaelduartepinheiro** [shprink/ionic-native-transitions#5]
Hi! I'm trying to figure out how to implement these screen transitions in a side menu based app, but the documentation is not clear about it. Is this feature planned?

**Comment by shprink** [comment]
Not sure if this is possible. Which documentation are you referring to?

**Comment by raphaelduartepinheiro** [comment]
Documentation of this repository. I mean, it's not clear if it is now implemented.

This plugin works great, but it's kind weird an app with a smooth transition (using this one) and the menu transition being laggy... 

ionic-native-transitions is getting popular, and the community is concerned about it.

I think this feature is very important, but it's not easy.

A way less complex to do it is using non-side-menu based app and simulate it through drawer, but a problem that comes to mind is testing the transition on browser.

**Comment by shprink** [comment]
The plugin is disabled when using the browser anyway. If you got some input on how to use the drawer to do this I am listening. I personally do not think it would be possible without changing the way the side menu works on ionic.

**Comment by ffabreti** [comment]
@raphaelduartepinheiro: Have you managed to do that? Can you share? I mean, using a additional view with drawer effect to simulate the ionic sidemenu?

**Comment by raphaelduartepinheiro** [comment]
@ffabreti Hi! :smile:  
unfortunately lately I haven't enough time to deal with these kind of things.. I've tried a time ago, but it's not that easy since you would drop the Ionic's side menu and create your own using this plugin paying attention with browser support as it's a native stuff. 

What I've noticed in my experience was: the drawer with the origin setted on left (like side menu) only animates a screenshot and if you try to click on the main screen to close menu, it doesn't work.

In my opinion Telerik Native Transition was not build thinking a complete transition solution. But must be a workaround... :smile:

**Comment by ffabreti** [comment]
@raphaelduartepinheiro : Thanks!
When I have time, I'll try to completely remove sidemenu and implement its content as a new view, so that it can be animated like any other view. I'm having trouble with sidemenu x phonegap-googlemaps-plugin because the latter requires webview transparency that fights with ionic sidemenu strategy.

**Comment by Kratos-SA** [comment]
+1
