### ISSUE TITLE
No more ionic-native-transitions.min.js?

### ISSUE THREAD

**Issue by nikolasleblanc** [shprink/ionic-native-transitions#51]
Bower install no longer provides minified file.

**Comment by shprink** [comment]
Hi, I am not familiar with Bower, can you check my bower.json file (that did not change for a long time)

https://github.com/shprink/ionic-native-transitions/blob/develop/bower.json#L5-L7

let me know if I need to make a change (for instance adding the .min version in the main array?).

PR welcome :)

**Comment by shprink** [comment]
Also you should upgrade to RC6

**Comment by nikolasleblanc** [comment]
My bower.json file was looking for shprink/ionic-native-transitions#~1.0.0-rc3, and the `~` tells it to grab anything equal to or newer than the release indicated, so looks like I am using rc6 already anyway, just for whatever reason the minified file that was in there is no longer included. Who knows, I minify on my end anyway, so we're all good, just updating my references. Thanks!
