### ISSUE TITLE
Pass `backCount` parameter to `$ionicNativeTransitions.goBack()` method

### ISSUE THREAD

**Issue by addi90** [shprink/ionic-native-transitions#53]
The `$ionicNativeTransitions.goBack()` internally uses `$ionicHistory.goBack()`. `$ionicNativeTransitions.goBack()` should allow users to pass the `backCount` as a parameter, allowing to go back a given number of views

**Comment by shprink** [comment]
Yep good idea :)

**Comment by addi90** [comment]
Do you want to work on this or I may give it a try?

**Comment by shprink** [comment]
Be my guest :)

**Comment by addi90** [comment]
@shprink Created the PR. Please take a look

**Comment by addi90** [comment]
@shprink I guess you can close this story

**Comment by shprink** [comment]
@addi90 I get this error on some cases:

![image](https://cloud.githubusercontent.com/assets/1388706/12379022/70a82156-bd16-11e5-9217-52bd645cacd3.png)

`Uncaught TypeError: Cannot read property 'viewId' of undefined`

**Comment by shprink** [comment]
Fixed in v1.0.0-rc9
