### ISSUE TITLE
Crosswalk with Keyboard causes flickering and stretch to header

### ISSUE THREAD

**Issue by confused-pv** [shprink/ionic-native-transitions#55]
Hi,

For crosswalk how to make sure flickering does not happen on keyboard action.

**Comment by shprink** [comment]
Can you try that: https://github.com/shprink/wordpress-hybrid-client/blob/develop/RELEASE.md#keyboard-adjustment

Are you sure this as anything to do with this plugin?

**Comment by confused-pv** [comment]
The problem is when I am using 
<preference name="CrosswalkAnimatable" value="true" />

even without this plugin the flickers exists. I was hoping if you have looked into that problem.

**Comment by confused-pv** [comment]
And if I change the Manifest file to android:windowSoftInputMode="adjustNothing" then I can not scroll inside the page even if keyboard is up.

**Comment by shprink** [comment]
can any of you send me your app in debug mode so I can reproduce? 

julien.renaux@toptal.com

**Comment by carydias** [comment]
@confused-pv it sounds like you are referring to the issue described in these two threads:
https://github.com/MobileChromeApps/mobile-chrome-apps/issues/538
https://github.com/driftyco/ionic-plugin-keyboard/issues/96

There is a video here:
https://www.youtube.com/watch?v=XPDd-ZFIE4k

The solution is to set CrosswalkAnimatable to false; which is now the default in CrossWalk.  This is fine for most applications, however this plugin requires the attribute to be set to true.

I'd assume there's no way to fix this unless the plugin can somehow function without CrosswalkAnimatable?

**Comment by carydias** [comment]
It appears you can fix it by setting the following in your AndroidManifest:
<activity android:windowSoftInputMode="adjustPan">

You'll also need to set Ionic to full screen mode since you are no longer using the resize option:
ionic.Platform.isFullScreen = true;

And fix whatever small issues this throws up.  It appears to be working well for me (for now).

**Comment by shprink** [comment]
Thanks @carydias for this :)

@confused-pv can you test and let us know if it works better?

**Comment by confused-pv** [comment]
Hi 

Thanks @carydias for the suggestion. The issue is if I remove adjustResize then it won't adjust the screen on keyboard up.  Pasting the google doc definitions.

And as I have quite a few screens where I need to adjust the screen I guess native transitions is out of scope for me ( at-least for now ) :(

From the google doc

"adjustResize"

The activity's main window is always resized to make room for the soft keyboard on screen.

"adjustPan"

The activity's main window is not resized to make room for the soft keyboard. Rather, the contents of the window are automatically panned so that the current focus is never obscured by the keyboard and users can always see what they are typing. This is generally less desirable than resizing, because the user may need to close the soft keyboard to get at and interact with obscured parts of the window.

**Comment by m52go** [comment]
Hi @carydias, can you clarify your solution? What do I need to add to AndroidManifest?

**Comment by carydias** [comment]
@m52go I have updated the comment with the right formatting.  Sorry about that.

@confused-pv You'll have to remove the following from your code if it's still in there:
`cordova.plugins.Keyboard.disableScroll(true);`

**Comment by uzumakinaruto123** [comment]
This line :- `<preference name="CrosswalkAnimatable" value="true" />`  is the issue ?

I think its crosswalk issue !
If we set `CrosswalkAnimatable` to `true` keyboard flickering occurs.

But, **ionic native transitions** requires it to be set true ! As soon as we make it false flickering will not occur but native transitions wont work !

Any help is appreciated !

**Comment by shprink** [comment]
Interesting. Have you tried the latest Crosswalk version?

**Comment by uzumakinaruto123** [comment]
yes ! today itself ! i use `ionic browser add crosswalk` command ! which i suppose always installs latest one..

**Comment by shprink** [comment]
I am not sure about that. 

try `ionic plugin add cordova-plugin-crosswalk-webview`

**Comment by uzumakinaruto123** [comment]
tried ! same behaviour :(

**Comment by AdrienDC** [comment]
It works like a charm @carydias ! by changing <activity android:windowSoftInputMode="adjustPan">
and put ionic.Platform.isFullScreen to true

For the android manifest, any workaround to make it permanent? because I guess when I'll rebuild this change will be lost?

**Comment by uzumakinaruto123** [comment]
yay !!! it really works !  i never used to do this `ionic.Platform.isFullScreen to true` since i thought the statusbar will be hidden. but i tried it today and works like charm.

along with  `<preference name="CrosswalkAnimatable" value="true" />`  this step...

I think folllowing steps by @carydias  should also go in docs ... since many are struggling with this

- setting `ionic.Platform.isFullScreen=true;` in app.js
- editing manifest to this `<activity android:windowSoftInputMode="adjustPan">`
- finally commenting/removing `cordova.plugins.Keyboard.disableScroll(true);` from app.js

Thanks , made my day

**Comment by carydias** [comment]
@AdrienDC interestingly Ionic doesn't overwrite the change made to the AndroidManifest when you build the platform again.

**Comment by Vishal0203** [comment]
@uzumakinaruto123  after browsing through many links, your suggestion worked.

**Comment by hxgqh** [comment]
@uzumakinaruto123 , it will cause another problem: after keyboard show up, the page can not be scrolled.

**Comment by uzumakinaruto123** [comment]
@hxgqh  i can scroll ! using the same solution ever since i posted and it works.

**Comment by hxgqh** [comment]
@uzumakinaruto123 what kind of modification did you make?  It's not working in my project.

**Comment by hxgqh** [comment]
I'm now using cordova-android@5.1.1

**Comment by uzumakinaruto123** [comment]
@hxgqh  same as i mentioned above. i do it in every project ! what i think is you missing the last step.
completely remove/comment this `cordova.plugins.Keyboard.disableScroll(true);`  and setting `ionic.Platform.isFullScreen to true`

**Comment by shprink** [comment]
can we close that issue if you guys found a way to make it work?

**Comment by uzumakinaruto123** [comment]
for me its solved . i have tested it in multiple projects. its ok to close :) since few other people also reported solving it.

**Comment by shprink** [comment]
awesome, thanks very much!

**Comment by hxgqh** [comment]
@uzumakinaruto123 I've already set ionic.Platform.isFullScreen to true. But still another problem: the input will be hidden by keyboard.

**Comment by uzumakinaruto123** [comment]
@hxgqh  i really dont know why is that ! but i can confirm that it focuses and page also scrolls. i currently have working app too in my phone.  ionic doesn't override maifest while building but still check if manifest changes are saved.

**Comment by luco** [comment]
@uzumakinaruto123 's fix works perfectly. Thanks a lot.

**Comment by Martin-Mo** [comment]
@hxgqh If you put your input inner ion-footer, you should add keyboard-attach to it. All other cases, i can scroll smoothly when the keyboard is up.

**Comment by inexuscore** [comment]
@uzumakinaruto123 oh my GAWD you saved my day T_T NOICE. I've been googling and struggling with this white flash of death after installing crosswalk, I was banging my head against the table just minutes ago 🗡 you made my day man 🥇 thank you, god bless you, Elune be with you and wait for it -- don't take this the wrong way -- but I love you so much right now I wanna send you some money 😅 Cheers!

**Comment by uzumakinaruto123** [comment]
@inexuscore  LOL ! Its ok  . happens when shit is open source. Glad , you solve it  👍

**Comment by inexuscore** [comment]
@uzumakinaruto123 true, this kinda stuff should get documented well, eh its goOd for now. will be migrating to Ionic 2 soOn. thanks again! 👍
