### ISSUE TITLE
How To "require('ionic-native-transitions');"?

### ISSUE THREAD

**Issue by alteredorange** [shprink/ionic-native-transitions#59]
This is probably a really dumb question, but where exactly do you put "require('ionic-native-transitions');"?  I tried putting it in ionic.app.scss and that doesn't seem to work.  Do I use a cli command or something?

**Comment by shprink** [comment]
```
require('ionic-native-transitions')
```

is only needed if you use commonJS or ES67 modules.

If you use bower and gulp/grunt you can import the script the same way you import any other dependencies.

it could be in your index.html:

```
<script src="../bower_components/ionic-native-transitions/dist/ionic-native-transitions.js"></script>
```

or via a build process.

let me know if you need more help,
julien

**Comment by shprink** [comment]
PS: there is no such a thing as a "dumb question", do not worry :)

**Comment by alteredorange** [comment]
Thanks for the quick response!  I added it to my index.html with   <script src="../node_modules/ionic-native-transitions/dist/ionic-native-transitions.js"></script> and I added 'ionic-native-transitions' to my app.js file, but it's still creating a blank screen for my app... (i.e. when I delete that stuff, my app shows up as normal) Do I need to add anything else?

**Comment by alteredorange** [comment]
I also installed the Cordova transition plugin, it's sitting in my plugins folder, do I need to call that at all?

**Comment by shprink** [comment]
What's the error message?

**Comment by alteredorange** [comment]
It just hangs... Is there a way to see an error log?  I'm using the cli and the gui interface.  In the gui interface it just hangs on trying to server the ionic-native js file.  When using the cli interface it just keeps trying to "run" the android app.

**Comment by alteredorange** [comment]
I just did a build with --verbose on the cli and it built just fine, but the app just has a white screen...  It says build was successful and doesn't show any errors that I can see...

**Comment by shprink** [comment]
Open the console of the app, using chrome dev tools, there must be an error there

**Comment by shprink** [comment]
If you want to chat => https://gitter.im/shprink/ionic-native-transitions

**Comment by dpa99c** [comment]
The installation section in the documentation also had me confused as it's primarily written for those using ES6 modules or another module loader. 
It also wasn't immediately clear that this is basically an Angular wrapper around the Telerik plugin hence both are required to be installed.

For simple folks like me, here's what I did to make it work:

- Install this module: `npm install ionic-native-transitions --save`
- Install the Telerik plugin: `ionic plugin add com.telerik.plugins.nativepagetransitions --save`
- Copy the dist file from `node_modules` into my `www/` folder: `cp ./node_modules/ionic-native-transitions/dist/ionic-native-transitions.min.js ./www/js/`
- Insert a script tag into index.html: `<script src="js/ionic-native-transitions.min.js"></script>`
- Include it in my app module and configure it:

    ```
    angular.module('iwalk', [
        'ionic',
       'ionic-native-transitions'
    ]).config(function($ionicNativeTransitionsProvider) {
        $ionicNativeTransitionsProvider.setDefaultTransition({
            type: 'slide',
            direction: 'left'
        });
        $ionicNativeTransitionsProvider.setDefaultBackTransition({
            type: 'slide',
            direction: 'right'
        });
   ```
