### ISSUE TITLE
Tabs transition

### ISSUE THREAD

**Issue by MatanYed** [shprink/ionic-native-transitions#64]
There is transition when changing tabs. It's should not happened.

Should be checked that the ui-sref directive isn't ion-tab directive....

**Comment by shprink** [comment]
It is in the doc:

Disable native transition for one state (for instance on tabs)

```
.state('home', {
    url: '/home',
    nativeTransitions: null,
    templateUrl: "templates/home.html"
})
```

**Comment by MatanYed** [comment]
It's wrong because on nested pages, clicking back won't be in native transition

**Comment by marciogurka** [comment]
I'm having the same issue. My code:

.state('tab', {
            url: '/tab',
            abstract: true,
            nativeTransitions: null,
            templateUrl: 'templates/tabs.html'
        })

.state('tab.file', {
            url: '/file',
            views: {
                'tab-file': {
                    templateUrl: 'templates/files.html',
                }
            }
        })

.state('tab.quiz', {
            url: '/quiz',
            views: {
                'tab-quiz': {
                    templateUrl: 'templates/quiz.html',
                }
            }
        })


But when I change from 'tab.files' to 'tab.quiz', all the view have transition. Is there a way to make the transition works only in the nested pages?

**Comment by shprink** [comment]
Maybe you can use the height offset option. I recommend not to use
transitions on tabs though

**Comment by kmturley** [comment]
Note that if you want to disable the animation forwards AND backwards you need two properties:

    .state('edit', {
        url: '/edit',
        nativeTransitions: null,
        nativeTransitionsBackAndroid: {
            duration: 0
        },
        templateUrl: 'components/edit/edit.html',
        controller: 'Edit'
    })
