### ISSUE TITLE
nativepagetransitions is disabled or nativepagetransitions plugin is not present

### ISSUE THREAD

**Issue by guidodipaolo** [shprink/ionic-native-transitions#65]
Hi !! 
I have installed ionic-native-transitions plugin in but I dont know why, the browser console show me the next message: 

**_"nativepagetransitions is disabled or nativepagetransitions plugin is not present" _**

1) I have added ionic-native-transitions in my app module 

`
    angular.module('RTVApp', [
      'ionic',
      'ngCordova',
      'ionic-native-transitions'
    ])`

2) I have added the dit file into my html file 

`
    <script src="lib/ionic/js/ionic.bundle.js"></script>
    <script src="lib/ngCordova/dist/ng-cordova.min.js"></script>
    <script src="lib/ionic-native-transitions/dist/ionic-native-transitions.min.js"></script>`

I really dont know what's happening. Can anyone helps me ?

**Comment by scamianbas** [comment]
Hi,
try this :  `ionic plugin add https://github.com/Telerik-Verified-Plugins/NativePageTransitions`

**Comment by guidodipaolo** [comment]
Hi @scamianbas  I dont want to change the plugin i want to solve this issue. 

Thanks !!

**Comment by shprink** [comment]
Thanks @scamianbas :)

He is right @guidodipaolo, you need to install this plugin too. Native transition only works on devices not on the browser obviously so the log message "nativepagetransitions is disabled or nativepagetransitions plugin is not present" that you get from the browser is correct.

**Comment by johnnynode** [comment]
That's really help!
