### ISSUE TITLE
How to disable back transitions completely

### ISSUE THREAD

**Issue by mohamed-ahmed** [shprink/ionic-native-transitions#67]
I'd like to globally disable transitions going back.
`$ionicNativeTransitionsProvider.setDefaultBackTransition(null)` 
didn't work for me.

**Comment by mohamed-ahmed** [comment]
@shprink Any thoughts on this?

**Comment by shprink** [comment]
you cannot. Why do you want transition forward but not backward BTW?

**Comment by mohamed-ahmed** [comment]
Because back transitions look awkward in my app. The transition animates but completes on the same page, then suddenly the previous page appears. Why wouldn't someone be able to navigate back without transition if they want to.

**Comment by shprink** [comment]
that's a legit use case I have not though about.

**Comment by mohamed-ahmed** [comment]
Thanks for considering this feature

**Comment by kmturley** [comment]
Setting the duration to 0 seems to be a good workaround:

        $ionicNativeTransitionsProvider.setDefaultBackTransition({
            type: 'slide',
            direction: 'left',
            duration: 0
        });

**Comment by shprink** [comment]
The workaround is good enough for now. thanks
