### ISSUE TITLE
Click issue during transitions

### ISSUE THREAD

**Issue by mertaksoy** [shprink/ionic-native-transitions#70]
I have a button on page A, that navigates me to page B. On page B i have an input field, that in same position as my button on page A.
So when i touch the button to navigate to page B, the input field on page B is also touched ( -> focus on input, keyboard activated). It only happens when i use the native transitions.

Ionic info:
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v0.12.2
Xcode version: Xcode 7.2 Build version 7C68

**Comment by shprink** [comment]
If the input is not at the exact same position, is it focused as well?

**Comment by yuzdeyuzmert** [comment]
No, it doesnt

**Comment by mertaksoy** [comment]
No, it doesnt

**Comment by gynekolog** [comment]
Same like https://github.com/shprink/ionic-native-transitions/issues/58

**Comment by shprink** [comment]
Any of you have had the time to debug it?

**Comment by AtulaGuleria** [comment]
Any updates

**Comment by gynekolog** [comment]
@shprink Yes but can't share app.

**Comment by AtulaGuleria** [comment]
not even a hint

**Comment by michaeldisaro** [comment]
I think it's something related to this http://developer.android.com/training/gestures/viewgroup.html

**Comment by danielptn** [comment]
same problem.. any solution?

**Comment by duddu** [comment]
even if it's an old question...
for posterity: with Ionic, a workaround is to use the "data-tap-disabled" attribute on the dom element that triggers the native transition. 
if you have no problems with this attribute and [its consequences](https://ionicframework.com/docs/api/page/tap/), this fix the issue.

**Comment by mertaksoy** [comment]
obsolete
