### ISSUE TITLE
How do we programmatically enable/disable an animation?

### ISSUE THREAD

**Issue by arashb31** [shprink/ionic-native-transitions#71]
How can I tell $ionicNativeTransitions to not use any transition programmatically?

E.g.

$scope.gotoItem = function(item) {
  $ionicNativeTransitions.gotoState('item-view', { item: item}, { type: "none" });
}

Also, I'm using the $ionicHistory to navigate back programmatically as well. How can I disable animations for those transitions?

E.g.

$scope.goBack = function() {
       //Here i'd like to disable back animation as it looks strange.
       $ionicHistory.goBack(); 
}

Overall, I'm looking for a way to trigger the animations only when I ask for them, with code, rather than have a default animation.
Right now, for example, I'm also getting animations when selecting tabs (which I don't want).

**Comment by shprink** [comment]
You can disable transitions in a router state level. It is all in the docs.
