### ISSUE TITLE
native transition for ionicmodal

### ISSUE THREAD

**Issue by Freundschaft** [shprink/ionic-native-transitions#72]
would a native transition for an ionicmodal overlay be possible from a technical perspective?

**Comment by shprink** [comment]
with the code as it is right now no but I believe it is doable.

**Comment by Freundschaft** [comment]
has this feature been added?

**Comment by shprink** [comment]
Nope, it is a #wontFix

**Comment by Freundschaft** [comment]
alright, thanks!
