### ISSUE TITLE
reassign of $rootScope.$ionicGoBack breaks native transitions

### ISSUE THREAD

**Issue by Freundschaft** [shprink/ionic-native-transitions#73]
in my app I need to change the behavior of ionicgoback briefly, so I reassign something else to $rootscope.$ionicgoback this causes native transitions to break, as the animation will come from the wrong direction.

**Comment by shprink** [comment]
Yes `ionicgoback` is used by this plugin. What do you do in this function anyway?

**Comment by Freundschaft** [comment]
I have a view where the back button should do something else instead of going back to the last view temporarily.
I worked around it by saving the original reference to $rootScope.$ionicGoBack and restoring it, that worked. Can be closed, but one has to be aware that meddling with ionicgoback can and will cause problems with the plugin :)
