### ISSUE TITLE
Ionic 2

### ISSUE THREAD

**Issue by katmai** [shprink/ionic-native-transitions#80]
is this compatible with ionic 2?

**Comment by shprink** [comment]
not yet

**Comment by kleeb** [comment]
are there any plans, or some roadmap for Ionic2?

**Comment by shprink** [comment]
not yet. Ionic2 animations are better though, is it still needed?

**Comment by kleeb** [comment]
hmm, haven't checked animations yet on I2, however on some slower devices native transition plugin worked awesome with ionic1
