### ISSUE TITLE
['NativePageTransitions'] took '13.155273' ms. Plugin should use a background thread.

### ISSUE THREAD

**Issue by addi90** [shprink/ionic-native-transitions#85]
I am getting this error while transtioning in my app in XCode. I think we need to make the transition to use a background thread for performance reasons

**Comment by shprink** [comment]
You should then create an issue on the cordova plugin repo => https://github.com/Telerik-Verified-Plugins/NativePageTransitions

**Comment by addi90** [comment]
Sure. Thanks
