### ISSUE TITLE
Installation Methods (Documentation)

### ISSUE THREAD

**Issue by alexjhannan** [shprink/ionic-native-transitions#88]
Hi! Great plugin here, I definitely recommend putting this into pretty much every Ionic application, as it significantly improves the user experience. However, I had some difficulty installing the plugin, so I wanted to list my steps in case they are helpful for anyone else.

Most of these steps were taken from various issues raised in this repo, but I couldn't find a single source that walked through the entire process. Here goes!

First up, run these commands in your Ionic app's directory:
```
bower install shprink/ionic-native-transitions
ionic io init
ionic plugin add https://github.com/Telerik-Verified-Plugins/NativePageTransitions
```

Then, add this line to your index.html:
```
<script src="./PathToBowerLib/dist/ionic-native-transitions.min.js"></script>
```

Finally, configure the $ionicNativeTransitionsProvider in your app.config. The docs do a great job of explaining this step!

Hope this helps someone out down the line.

**Comment by jdnichollsc** [comment]
Agree, the documentation is very important and this plugin is very useful :dancers:

**Comment by martyzz1** [comment]
I came from here  http://scottbolinger.com/4-ways-to-make-your-ionic-app-feel-native/

And the example they give is now slightly out of date. 
$ionicNativeTransitionsProvider.setOptions({
should be 
$ionicNativeTransitionsProvider.setDefaultOptions({
