### ISSUE TITLE
Support for Ionic Modals?

### ISSUE THREAD

**Issue by alexjhannan** [shprink/ionic-native-transitions#89]
Is there any way to use these native transitions inside of an $ionicModal? Since these transitions are a lot smoother than what Ionic provides, my team is looking to integrate them across the board, but one of our apps relies pretty heavily on modals at the moment. The only solution I know of right now is to swap out the modals for Angular states, so that the native transitions continue to fire off, but that's not exactly ideal.

Thanks for any info! Great plugin!

**Comment by shprink** [comment]
There is no good solution for modals for now.

**Comment by alexjhannan** [comment]
Thanks for the answer! Are there any plans to extend this plugin to modals, or any techniques that you could suggest to deal with this issue? I may propose moving away from modals to my team for a better overall app experience.

**Comment by shprink** [comment]
I believe it is technically doable by listening to the modal live cycle events. It would require a little bit of work, do not know if I have the time but it could be an interesting feature.

**Comment by alexjhannan** [comment]
Hey! My team is looking to include these transitions for the modals on our application. It's a significant amount of refactoring to swap them out to views. I'm wondering if the time spent refactoring would be better spent trying to flesh out modal functionality for this plugin.

Is it possible for your to give some direction on where to start and how to implement this feature? If the time commitment is similar to what it would be for us to refactor the modals in our application (1-2 days of coding), we're probably better served by expanding this plugin, and I'll get to contribute something back.

Anyway, let me know when possible, as we've got clients waiting! Cheers.

**Comment by shprink** [comment]
You can easily call your transition right before opening the modal:

```
window.plugins.nativepagetransitions.slide(options, transitionSuccess, transitionError)
```

and call this on modal opened:

```
window.plugins.nativepagetransitions.executePendingTransition();
```

**Comment by alexjhannan** [comment]
Thanks, I'll try this out right away.

**Comment by alexjhannan** [comment]
I've plumbed this through to a number of our modals, and things are already looking much smoother. Thanks so much for your help.

If possible, could you send a list of the parameters that the option object can take?

**Comment by shprink** [comment]
check the Readme and the Telerik docs.

**Comment by alexjhannan** [comment]
Thanks!

**Comment by DaDanny** [comment]
Could you please expand on how you did this with modals @alexjhannan ? I'm working on that now as well.


Thanks!
