### ISSUE TITLE
Package pulled from bower?

### ISSUE THREAD

**Issue by Mathius17** [shprink/ionic-native-transitions#90]
A new team member was installing all of our bower dependencies and this one didn't even appear in bower search.

Went to look it the bower page but had no results either: http://bower.io/search/?q=ionic-native-transitions

This installation method is still listed in the documentation, should be either remove form the docs, or added back to bower.

**Comment by shprink** [comment]
it is not listed in bower search but can be installed via bower anyway.

Julien Renaux
Software Engineer
Blog <http://julienrenaux.fr/> - Twitter <https://twitter.com/julienrenaux>
- Hire me on Toptal
<http://www.toptal.com/resume/julien-renaux#select-just-supreme-hackers>
