### ISSUE TITLE
Thread warning on iOS

### ISSUE THREAD

**Issue by pliablepixels** [shprink/ionic-native-transitions#93]
Hi there, when using the plugin on iOS, each state/view transition produces
```
2016-04-17 14:53:39.473 zmNinja[5560:3283442] THREAD WARNING: ['NativePageTransitions'] took '59.498779' ms. Plugin should use a background thread.
```

Any suggestions on how to avoid this? Its probably benign but I'd love to know if there is a way around it

**Comment by shprink** [comment]
It is just a warning. If you want to ask more about it please ask in the cordova plugin repo => https://github.com/Telerik-Verified-Plugins/NativePageTransitions

**Comment by pliablepixels** [comment]
Thanks - for future reference, what is the difference between the telerik plugin and your repo ? Is yours an angular wrapper around it ? I'd like to make sure I know the scope of where your plugin ends so  I can post issues to the right  repo in future. thx

**Comment by shprink** [comment]
You got it right.
