### ISSUE TITLE
Nav bar hidden by property hide-nav-bar="true" appears during transition

### ISSUE THREAD

**Issue by jmanlapid** [shprink/ionic-native-transitions#94]
I have an issue on iOS where for when <ion-view> has the hide-nav-bar="true" property on it. When I transition to another state, the nav bar abruptly appears and pushes the content down for the duration of the animation. 

`
<ion-view view-title="WELCOME" hide-nav-bar="true" has-bouncing="false"> 
`

**Comment by kenmickles** [comment]
@jmanlapid a couple questions:

1. Do you have any transition options set (slowdownfactor, iosdelay, etc.) or is your app using the defaults?
2. Is your app using UIWebView or the WKWebView plugin?
3. Can you paste the output of the `ionic info` command?

**Comment by jmanlapid** [comment]
@kenmickles 

1. { type: 'slide', direction: 'right'}

2. Using UIWebView

3. Ionic Framework Version: 1.2.1
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: 1.8.5
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.2.4
Xcode version: Xcode 7.3.1 Build version 7D1014

4. Also - native transitions version is 0.6.4

**Comment by kenmickles** [comment]
Thanks, @jmanlapid! I created [a sample project over here](https://github.com/kenmickles/native-transition-test) to test out the bug. You can find the native transition code in the [tab-chats](https://github.com/kenmickles/native-transition-test/blob/master/www/templates/tab-chats.htm) and [chat-detail](https://github.com/kenmickles/native-transition-test/blob/master/www/templates/chat-detail.html) templates.

I think I'm seeing the issue you describe when I tap the back button on chat-detail. It looks like this:

![bad_transition](https://cloud.githubusercontent.com/assets/108583/16349455/0a65b2f8-3a27-11e6-936c-ee9dd92ca40e.gif)

I'm not seeing the bug when I activate the transition from somewhere other than the default back button. i.e. here I've replaced the back button with a generic button inside `<ion-nav-buttons>` and it's working OK:

![good_transition](https://cloud.githubusercontent.com/assets/108583/16349498/42c12c5e-3a27-11e6-866a-5ea787dfe893.gif)

So, if that is actually the bug you're seeing, there's a workaround you could try. Failing that, I'd recommend trying these steps (in order of how much work they'll be):

1. Update ionic-native-transitions and NativePageTransitions
2. Update Ionic to 1.3
3. Swap out UIWebView for WKWebView with the [cordova-plugin-wkwebview-engine](https://github.com/apache/cordova-plugin-wkwebview-engine). I've generally found WKWebView to work better with with the native transitions plugin (and it's just faster in general). However, it doesn't work with Angular templates loaded over XHR, so you'll end up going down the path of using something like [gulp-angular-templatecache](https://github.com/miickel/gulp-angular-templatecache) or (gross) running a local web proxy in the app.

Sorry if that doesn't solve the problem, but hopefully the info is helpful!
