### ISSUE TITLE
setDefaultBackTransition issue

### ISSUE THREAD

**Issue by miyamotomusashi** [shprink/ionic-native-transitions#95]
Hi. I use verison 0.6.2. I have a problem about setDefaultBackTransition. I use like below:

      $ionicNativeTransitionsProvider.setDefaultTransition({
          type: 'slide',
          direction: 'left'
      });

     $ionicNativeTransitionsProvider.setDefaultBackTransition({
         type: 'slide',
         direction: 'right'
     });

backtransition  works same as defaulttransition. I tried other transition styles also. It did same thing. I made research but I did not fix this problem. Thansk in advance.

**Comment by Tronix117** [comment]
I have the same issue, only physical back button is doing the good transition, and setDefaultBackTransition has no effect. @miyamotomusashi you closed it so I assume you solved your issue, can you maybe post how ?
