### ISSUE TITLE
The transition is not right on IOS with Ionic 1.3.0

### ISSUE THREAD

**Issue by xjy0925** [shprink/ionic-native-transitions#97]
If the transition is from A to B on IOS
normal case:  A --> B
But it is:   A turn to B immediately, then B --> B

**Comment by spacegraym3** [comment]
I am running into the exact same issue!

**Comment by spacegraym3** [comment]
I noticed this issue happens mostly when you the side menu is open and you navigate from one view to another.  I noticed it severely if the state URL had different starting paths.

For example:

/foo/A -> /bar/B showed the issue
/foo/A -> /foo/B did not even though the contents are not changed.

**Comment by metalaureate** [comment]
I have the same problem.

**Comment by metalaureate** [comment]
Here's a video of the bug:

![ios_native_transitions](https://cloud.githubusercontent.com/assets/2185884/15093462/d4e3f40a-143d-11e6-9671-7622122139bf.gif)

**Comment by shprink** [comment]
You can play with the `triggerTransitionEvent` option. You could use another event from the ui router or create your own event that delays `$ionicView.afterEnter` a bit.

```
.config(function($ionicNativeTransitionsProvider){
    $ionicNativeTransitionsProvider.setDefaultOptions({
        triggerTransitionEvent: '$ionicView.afterEnter', // internal ionic-native-transitions option
    });
});
```

**Comment by metalaureate** [comment]
@shprink Thanks for the quick response - and thank you for working on project. It's a huge upgrade in hybrid app experience especially for Android. For iOS, could you clarify a bit further? I'm not sure I followed. How can I delay `$ionicView.afterEnter` and if I do, won't that make it worse? How do we stop the target view from rendering before the transaction has completed?

**Comment by shprink** [comment]
Try another event see how it goes. I would try `$ionicView.beforeEnter	` and maybe add a delay to it.

http://ionicframework.com/docs/api/directive/ionView/

**Comment by spacegraym3** [comment]
Is there anyway to do the following:

1. Start transition creates the UI snapshot (default behavior)
2. Beginning of transition animation is guaranteed to not start until the next view is rendered (i.e. after beforeEnter method execute is complete?

I know there is an option of when to trigger the transition but it has not seemed to work.

What I don't understand is why the following cannot be accomplished:

1. Transition start (take screenshot of current state)
2. Go to the next state (UI does not visually change.  Still shows screenshot taken in step 1)
3. Wait for a trigger.  In the current case, the view in one of its 'enter' states calls a method initiating transition.
4. Screenshot of next view that is now ready based on step (3)
5. Transition starts
6. Transition ends

**Comment by shprink** [comment]
what you are stating is the default. the event works if `-1` is set for `iosdelay` and `androiddelay` (default) in the config

```
.config(function($ionicNativeTransitionsProvider){
    $ionicNativeTransitionsProvider.setDefaultOptions({
        iosdelay: -1, // ms to wait for the iOS webview to update before animation kicks in, default -1
        androiddelay: -1, // same as above but for Android, default -1
        winphonedelay: -1, // same as above but for Windows Phone, default -1
    });
});
```

**Comment by metalaureate** [comment]
@shprink Picking up on @spacegraym3, those are my defaults in the example I posted above. Step #2 happens (render next state) but it is *not suppressed* in the UI. 

Changing the event to `beforeEnter` didn't fix the problem. I don't know how to add a delay to that event. Where in the code can I do that? 

I must confess that I do not understand what adding a delay would have to do with the bug we're reporting. That would only make the plugin wait even longer to render the transition, exposing the bug (the failure to suppress the changed state) even longer on the screen. I must be missing something.

**Comment by metalaureate** [comment]
Same issue presumbly https://github.com/shprink/ionic-native-transitions/issues/78

**Comment by metalaureate** [comment]
Maybe I am hopelessly confused, but @spacegraym3 commit of 10 days ago fixes my issue: https://github.com/spacegraym3/ionic-native-transitions/blob/40e3e897c79e9396e1ddc684f8ebae275019585e/dist/ionic-native-transitions.js

**Comment by xjy0925** [comment]
I'v tried to use event 'beforeEnter'  and use @spacegraym3 's commit, but the issue is still there.

**Comment by metalaureate** [comment]
@xjy0925 I should have clarified that it only works if I change state programmatically using `$ionicNativeTransitions.stateGo()`  https://github.com/shprink/ionic-native-transitions#state

**Comment by xjy0925** [comment]
@metalaureate Thanks your clarify!
This problem is not exists with Ionic 1.2.4, It appears after i update to Ionic 1.3.0.
Now I can work around it with $ionicNativeTransitions.stateGo.

**Comment by xjy0925** [comment]
@spacegraym3 's commit add '$timeout' in stateGo,  and should add '$timeout' for goBack also.

**Comment by spacegraym3** [comment]
Have you guys tried using the 
http://plugins.telerik.com/cordova/plugin/native-page-transitions 0.6.4 version?

**Comment by xjy0925** [comment]
Yes, the version i used is 0.6.4
"version": "0.6.4",
  "name": "com.telerik.plugins.nativepagetransitions"

**Comment by tskweres** [comment]
Any way to solve this?

**Comment by amilino** [comment]
@tskweres Switching from slide to fade effect until guys fix it.

**Comment by guyromb** [comment]
issue still exists with ionic@1.3.1
timeout doesn't seem to solve this problem

**Comment by amilino** [comment]
I was so happy when I found this, and now it doesn't work with latest version of Ionic. :(

**Comment by metalaureate** [comment]
@guyromb @amilino did you try replacing your ionic-native.transitions.js with https://github.com/spacegraym3/ionic-native-transitions/blob/40e3e897c79e9396e1ddc684f8ebae275019585e/dist/ionic-native-transitions.js

and only use 

`$ionicNativeTransitions.stateGo()` https://github.com/shprink/ionic-native-transitions#state

(vs. `sref-ui=''`)

That's what worked for me.

**Comment by tskweres** [comment]
@amilino adding the timeouts in ionic-native-transitions.js worked for me for all links and transition types.

Still disappointed that I can't dynamically change the fixedPixelBottom though, on some pages I have tabs and on some I don't :(

**Comment by amilino** [comment]
@guyromb What about goBack function?

**Comment by amilino** [comment]
@tskweres Oh it's in the workaround. Great, will test it on iPhone tomorrow.

**Comment by shprink** [comment]
@tskweres what do you mean you cannot change `fixedPixelBottom` per state? It should work. have you tried?

**Comment by amilino** [comment]
This doesn't work on iPhone, unfortunately.

**Comment by amilino** [comment]
Sorry I was referencing on bundle.min.js file. It's working!

**Comment by shprink** [comment]
New version => https://github.com/shprink/ionic-native-transitions/tree/v1.0.0-rc11

Please re-open the issue if not fixed.

**Comment by tskweres** [comment]
@shprink I am able to use $ionicNativeTransitionsProvider to set the fixedPixelsBottom in the .config

However, in my controllers, I want to be able to change this. In some states, I want my fixedPixelsBottom to be 0, and in other states ( where I have tabs ) I want the fixedPixelsBottom to be 44. 

Is it possible to change the defaultOptions from controllers?

**Comment by shprink** [comment]
Ad I explained, every state can have its own config.

https://github.com/shprink/ionic-native-transitions#usage

**Comment by guyromb** [comment]
Seems like the issue is back (not clear why). I tried to use @se1exin and @shprink repositories. I think I might update my plugins - but I don't see any change for telerik or ionic. Any idea?

**Comment by shprink** [comment]
with v1.0.0-rc11 @guyromb ?

**Comment by se1exin** [comment]
@guyromb what plugins do you have installed, what is your ionic version, and what call are you using to change state?

**Comment by guyromb** [comment]
Ops! I don't know why but bower kept on installing rc9 (maybe caching / default?). In my bower.json file I have:
`"ionic-native-transitions": "shprink/ionic-native-transitions"`
I changed it manually to
`"ionic-native-transitions": "shprink/ionic-native-transitions#1.0.0-rc11"`
and it seems to work now.

Thanks !

**Comment by tskweres** [comment]
@shprink I see that, would it look like this?

```
.state('home', {
    url: '/home',
    nativeTransitions: {
        "type": "slide",
        "direction": "left",
        "fixedPixelsBottom": 44
    }
    templateUrl: "templates/home.html"
})
.state('login', {
    url: '/login',
    nativeTransitions: {
        "type": "flip",
        "direction": "up",
        "fixedPixelsBottom": 0
    }
    templateUrl: "templates/login.html"
})
```

**Comment by tskweres** [comment]
@shprink works great, thanks!

**Comment by AdrienDC** [comment]
rc11 is working when I do:
                ```
$ionicNativeTransitions.stateGo('settings', {}, {
                    "type": "slide",
                    "direction": "right", // 'left|right|up|down', default 'left' (which is like 'next')
                    "duration": 300, // in milliseconds (ms), default 400
                });
```

but not with:
`$state.go("settings");`

```
      .state('settings', {
        url: '/settings',
        views: {
          'tab1': {
            /*            templateUrl: 'templates/settings.html',*/
            templateUrl: 'settings.html',
            controller: 'settingsCtrl'
          }
        },
        nativeTransitions: {
          "type": "slide",
          "direction": "right"
        }
      })
```
