### ISSUE TITLE
crash with ionic 1.3 angular 1.5 on android

### ISSUE THREAD

**Issue by harellevy** [shprink/ionic-native-transitions#98]
at the first moment i try to reach a view that native transition enabled app crashes always.

**Comment by shprink** [comment]
I do not think the Ionic or Angular version has anything to do with the app crash. 

The Telerik plugin version and the cordova android version might. Any clues on the logs?

**Comment by harellevy** [comment]
telerik version 0.6.2

falling on this line in cordova.js
    var msgs = nativeApiProvider.get().exec(bridgeSecret, service, action, callbackId, argsJson);

**Comment by harellevy** [comment]
no issue, just needed to use default options

**Comment by shprink** [comment]
Closing then
