### ISSUE TITLE
nativepagetransitions is disabled or nativepagetransitions plugin is not present

### ISSUE THREAD

**Issue by 312977** [shprink/ionic-native-transitions#99]
nativepagetransitions is disabled or nativepagetransitions plugin is not present

why?  i am add below code   and used  ionic-native-transitions.min.js in index.html,

var ngss = angular.module('starter', [
        'ionic', 'starter.controllers', 'starter.Paramcontrollers', 'starter.services', 'ionic-native-transitions',
        'starter.routes', 'ngResource', 'starter.Directive',
         'ngCordova', 'starter.MyInfocontrollers', 'starter.ProjectListController', 'starter.SellingController'
])
.config(function($ionicNativeTransitionsProvider){
        $ionicNativeTransitionsProvider.setDefaultOptions({
            duration: 400, // in milliseconds (ms), default 400,
            slowdownfactor: 4, // overlap views (higher number is more) or no overlap (1), default 4
            iosdelay: -1, // ms to wait for the iOS webview to update before animation kicks in, default -1
            androiddelay: -1, // same as above but for Android, default -1
            winphonedelay: -1, // same as above but for Windows Phone, default -1,
            fixedPixelsTop: 0, // the number of pixels of your fixed header, default 0 (iOS and Android)
            fixedPixelsBottom: 0, // the number of pixels of your fixed footer (f.i. a tab bar), default 0 (iOS and Android)
            triggerTransitionEvent: '$ionicView.afterEnter', // internal ionic-native-transitions option
            backInOppositeDirection: false // Takes over default back transition and state back transition to use the opposite direction transition to go back
        });
       
    })
    .config(function($ionicNativeTransitionsProvider){
        $ionicNativeTransitionsProvider.setDefaultTransition({
            type: 'slide',
            direction: 'left'
        });
    })
    .config(function($ionicNativeTransitionsProvider){
        $ionicNativeTransitionsProvider.setDefaultBackTransition({
            type: 'slide',
            direction: 'right'
        });
    })

**Comment by shprink** [comment]
You should start by removing all the config you added. It is all optional.

Only adding `'ionic-native-transitions'` as a dependency is required.

I assume you are testing on device?

**Comment by 312977** [comment]
i  removed that,   'ionic-native-transitions'  dependency  added;
and i esting on device andrion4.4          ionic cli 1.1.14   cordova 6.1.1

but still get:   nativepagetransitions is disabled or nativepagetransitions plugin is not present

**Comment by shprink** [comment]
Have you installed the cordova plugin?

**Comment by 312977** [comment]
I use  bower install shprink/ionic-native-transitions


and  then add ionic-native-transitions.min.js  to index.html   ,is wrong?

**Comment by 312977** [comment]
sorry  i am not    installed the cordova plugin.
now  I am  successed;thank you very much

**Comment by shprink** [comment]
I curious about why you missed that part? Is the docs no clear enough?

**Comment by 312977** [comment]
no   i am chinase ,english  not very well,

but  i thank  write  like this  ,May be more clearly

Requiry step:   1.install cordova plugin
                        2.npm install ionic-native-transitions 
                            or bower install shprink/ionic-native-transitions
                           or....
                        3.......
This is only my idea     ,thanks  agin
